
// This file has been generated by the GUI designer. Do not modify.
namespace CollapseFrameWidget
{
	public partial class CollapseFrame
	{
		private global::Gtk.Table CollapseFrameTable;
		
		private global::Gtk.Alignment CollapseFrameAlignment;
		
		private global::Gtk.EventBox CollapseFrameEventbox;
		
		private global::Gtk.Arrow CollapseFrameArrow;
		
		private global::Gtk.Label CollapseFrameLabel;
		
		private global::Gtk.VSeparator CollapseFrameVSeparator;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CollapseFrameWidget.CollapseFrame
			global::Stetic.BinContainer.Attach (this);
			this.Name = "CollapseFrameWidget.CollapseFrame";
			// Container child CollapseFrameWidget.CollapseFrame.Gtk.Container+ContainerChild
			this.CollapseFrameTable = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.CollapseFrameTable.Name = "CollapseFrameTable";
			// Container child CollapseFrameTable.Gtk.Table+TableChild
			this.CollapseFrameAlignment = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.CollapseFrameAlignment.Name = "CollapseFrameAlignment";
			this.CollapseFrameTable.Add (this.CollapseFrameAlignment);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.CollapseFrameTable [this.CollapseFrameAlignment]));
			w1.TopAttach = ((uint)(1));
			w1.BottomAttach = ((uint)(2));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child CollapseFrameTable.Gtk.Table+TableChild
			this.CollapseFrameEventbox = new global::Gtk.EventBox ();
			this.CollapseFrameEventbox.Name = "CollapseFrameEventbox";
			// Container child CollapseFrameEventbox.Gtk.Container+ContainerChild
			this.CollapseFrameArrow = new global::Gtk.Arrow (((global::Gtk.ArrowType)(3)), ((global::Gtk.ShadowType)(2)));
			this.CollapseFrameArrow.Events = ((global::Gdk.EventMask)(256));
			this.CollapseFrameArrow.Name = "CollapseFrameArrow";
			this.CollapseFrameEventbox.Add (this.CollapseFrameArrow);
			this.CollapseFrameTable.Add (this.CollapseFrameEventbox);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.CollapseFrameTable [this.CollapseFrameEventbox]));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child CollapseFrameTable.Gtk.Table+TableChild
			this.CollapseFrameLabel = new global::Gtk.Label ();
			this.CollapseFrameLabel.Name = "CollapseFrameLabel";
			this.CollapseFrameLabel.Xalign = 0F;
			this.CollapseFrameLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>CollapseFrameLabel</b>");
			this.CollapseFrameLabel.UseMarkup = true;
			this.CollapseFrameTable.Add (this.CollapseFrameLabel);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.CollapseFrameTable [this.CollapseFrameLabel]));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child CollapseFrameTable.Gtk.Table+TableChild
			this.CollapseFrameVSeparator = new global::Gtk.VSeparator ();
			this.CollapseFrameVSeparator.Name = "CollapseFrameVSeparator";
			this.CollapseFrameTable.Add (this.CollapseFrameVSeparator);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.CollapseFrameTable [this.CollapseFrameVSeparator]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.CollapseFrameTable);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.CollapseFrameEventbox.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnCollapse);
		}
	}
}
