CC=
FLAGS=-c -g -Os -Wall -fno-exceptions -ffunctions-sections -fdata-sections -mmcu=atmega32u4 -DF_CPU=16000000L -MMD -DUSB_VID=0x2341 -DUSB+PID=0x8036 -DARDUINO=106

LIBS=-I
BINARY=controlino

all:

clear:
