
// This file has been generated by the GUI designer. Do not modify.
namespace Frontend
{
	public partial class PreferencesDialog
	{
		private global::Gtk.Notebook notebook1;
		
		private global::Gtk.Table table2;
		
		private global::Gtk.CheckButton cbAutoConnect;
		
		private global::Gtk.CheckButton cbDebuggingMode;
		
		private global::Gtk.CheckButton cbLoadLastConfig;
		
		private global::Gtk.CheckButton cbMaximizedStart;
		
		private global::Gtk.CheckButton checkbutton1;
		
		private global::Gtk.HSeparator hseparator1;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.Label label12;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Table table3;
		
		private global::Gtk.Button btnLogFilePath;
		
		private global::Gtk.ComboBox cboxLogLevel;
		
		private global::Gtk.CheckButton cbtnenablelogging;
		
		private global::Gtk.Entry entryLogFilePath;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Frontend.PreferencesDialog
			this.Name = "Frontend.PreferencesDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child Frontend.PreferencesDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			this.notebook1.TabPos = ((global::Gtk.PositionType)(0));
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.table2 = new global::Gtk.Table (((uint)(6)), ((uint)(3)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			this.table2.BorderWidth = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.cbAutoConnect = new global::Gtk.CheckButton ();
			this.cbAutoConnect.CanFocus = true;
			this.cbAutoConnect.Name = "cbAutoConnect";
			this.cbAutoConnect.Label = global::Mono.Unix.Catalog.GetString ("Try to connect automaticly to a available device.");
			this.cbAutoConnect.DrawIndicator = true;
			this.cbAutoConnect.UseUnderline = true;
			this.table2.Add (this.cbAutoConnect);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2 [this.cbAutoConnect]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.cbDebuggingMode = new global::Gtk.CheckButton ();
			this.cbDebuggingMode.CanFocus = true;
			this.cbDebuggingMode.Name = "cbDebuggingMode";
			this.cbDebuggingMode.Label = global::Mono.Unix.Catalog.GetString ("Enable debugging mode");
			this.cbDebuggingMode.Active = true;
			this.cbDebuggingMode.DrawIndicator = true;
			this.cbDebuggingMode.UseUnderline = true;
			this.table2.Add (this.cbDebuggingMode);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2 [this.cbDebuggingMode]));
			w3.TopAttach = ((uint)(5));
			w3.BottomAttach = ((uint)(6));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.cbLoadLastConfig = new global::Gtk.CheckButton ();
			this.cbLoadLastConfig.CanFocus = true;
			this.cbLoadLastConfig.Name = "cbLoadLastConfig";
			this.cbLoadLastConfig.Label = global::Mono.Unix.Catalog.GetString ("Try to load last configuration");
			this.cbLoadLastConfig.DrawIndicator = true;
			this.cbLoadLastConfig.UseUnderline = true;
			this.table2.Add (this.cbLoadLastConfig);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2 [this.cbLoadLastConfig]));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.cbMaximizedStart = new global::Gtk.CheckButton ();
			this.cbMaximizedStart.CanFocus = true;
			this.cbMaximizedStart.Name = "cbMaximizedStart";
			this.cbMaximizedStart.Label = global::Mono.Unix.Catalog.GetString ("Enable maximization on start");
			this.cbMaximizedStart.DrawIndicator = true;
			this.cbMaximizedStart.UseUnderline = true;
			this.table2.Add (this.cbMaximizedStart);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2 [this.cbMaximizedStart]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.checkbutton1 = new global::Gtk.CheckButton ();
			this.checkbutton1.CanFocus = true;
			this.checkbutton1.Name = "checkbutton1";
			this.checkbutton1.Label = global::Mono.Unix.Catalog.GetString ("checkbutton1");
			this.checkbutton1.Active = true;
			this.checkbutton1.DrawIndicator = true;
			this.checkbutton1.UseUnderline = true;
			this.table2.Add (this.checkbutton1);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2 [this.checkbutton1]));
			w6.TopAttach = ((uint)(4));
			w6.BottomAttach = ((uint)(5));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.table2.Add (this.hseparator1);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2 [this.hseparator1]));
			w7.TopAttach = ((uint)(3));
			w7.BottomAttach = ((uint)(4));
			w7.RightAttach = ((uint)(3));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.Xalign = 0F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Debugging mode:");
			this.table2.Add (this.label11);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table2 [this.label11]));
			w8.TopAttach = ((uint)(5));
			w8.BottomAttach = ((uint)(6));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.Xalign = 0F;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Load last configuration:");
			this.table2.Add (this.label12);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table2 [this.label12]));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xalign = 0F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Attempt automatic connection:");
			this.table2.Add (this.label6);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table2 [this.label6]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xalign = 0F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Expert mode:");
			this.table2.Add (this.label7);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2 [this.label7]));
			w11.TopAttach = ((uint)(4));
			w11.BottomAttach = ((uint)(5));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.Xalign = 0F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Start maximized:");
			this.table2.Add (this.label8);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2 [this.label8]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook1.Add (this.table2);
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("General");
			this.notebook1.SetTabLabel (this.table2, this.label1);
			this.label1.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.table3 = new global::Gtk.Table (((uint)(4)), ((uint)(3)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			this.table3.BorderWidth = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.btnLogFilePath = new global::Gtk.Button ();
			this.btnLogFilePath.TooltipMarkup = "Select a folder to save the log file in.";
			this.btnLogFilePath.CanFocus = true;
			this.btnLogFilePath.Name = "btnLogFilePath";
			this.btnLogFilePath.UseUnderline = true;
			global::Gtk.Image w14 = new global::Gtk.Image ();
			w14.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-open", global::Gtk.IconSize.Menu);
			this.btnLogFilePath.Image = w14;
			this.table3.Add (this.btnLogFilePath);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table3 [this.btnLogFilePath]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.LeftAttach = ((uint)(2));
			w15.RightAttach = ((uint)(3));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.cboxLogLevel = global::Gtk.ComboBox.NewText ();
			this.cboxLogLevel.Name = "cboxLogLevel";
			this.table3.Add (this.cboxLogLevel);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table3 [this.cboxLogLevel]));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(3));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.cbtnenablelogging = new global::Gtk.CheckButton ();
			this.cbtnenablelogging.CanFocus = true;
			this.cbtnenablelogging.Name = "cbtnenablelogging";
			this.cbtnenablelogging.Label = global::Mono.Unix.Catalog.GetString ("enable logging");
			this.cbtnenablelogging.DrawIndicator = true;
			this.cbtnenablelogging.UseUnderline = true;
			this.table3.Add (this.cbtnenablelogging);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table3 [this.cbtnenablelogging]));
			w17.TopAttach = ((uint)(2));
			w17.BottomAttach = ((uint)(3));
			w17.LeftAttach = ((uint)(1));
			w17.RightAttach = ((uint)(2));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entryLogFilePath = new global::Gtk.Entry ();
			this.entryLogFilePath.CanFocus = true;
			this.entryLogFilePath.Name = "entryLogFilePath";
			this.entryLogFilePath.IsEditable = false;
			this.entryLogFilePath.InvisibleChar = '●';
			this.table3.Add (this.entryLogFilePath);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table3 [this.entryLogFilePath]));
			w18.TopAttach = ((uint)(1));
			w18.BottomAttach = ((uint)(2));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.Xalign = 0F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Diagnostics-file path:");
			this.table3.Add (this.label10);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table3 [this.label10]));
			w19.TopAttach = ((uint)(1));
			w19.BottomAttach = ((uint)(2));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Use system logger:");
			this.table3.Add (this.label2);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table3 [this.label2]));
			w20.TopAttach = ((uint)(2));
			w20.BottomAttach = ((uint)(3));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.Xalign = 0F;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Log Level:");
			this.table3.Add (this.label9);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table3 [this.label9]));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook1.Add (this.table3);
			global::Gtk.Notebook.NotebookChild w22 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.table3]));
			w22.Position = 1;
			// Notebook tab
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("System Logger");
			this.notebook1.SetTabLabel (this.table3, this.label5);
			this.label5.ShowAll ();
			w1.Add (this.notebook1);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(w1 [this.notebook1]));
			w23.Position = 0;
			// Internal child Frontend.PreferencesDialog.ActionArea
			global::Gtk.HButtonBox w24 = this.ActionArea;
			w24.Name = "dialog1_ActionArea";
			w24.Spacing = 10;
			w24.BorderWidth = ((uint)(5));
			w24.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w25 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w24 [this.buttonCancel]));
			w25.Expand = false;
			w25.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w26 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w24 [this.buttonOk]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 628;
			this.DefaultHeight = 478;
			this.checkbutton1.Hide ();
			this.label7.Hide ();
			this.Show ();
			this.cbMaximizedStart.Toggled += new global::System.EventHandler (this.OnCbMaximizedStartToggled);
			this.cbLoadLastConfig.Toggled += new global::System.EventHandler (this.OnCbAutoConnectToggled);
			this.cbDebuggingMode.Toggled += new global::System.EventHandler (this.OnCbDebuggingModeToggled);
			this.cbAutoConnect.Toggled += new global::System.EventHandler (this.OnCbAutoConnectToggled);
			this.cbtnenablelogging.Toggled += new global::System.EventHandler (this.OnCbtnenableloggingToggled);
			this.cboxLogLevel.Changed += new global::System.EventHandler (this.OnCboxLogLevelChanged);
			this.btnLogFilePath.Clicked += new global::System.EventHandler (this.OnBtnLogFilePathClicked);
		}
	}
}
