
// This file has been generated by the GUI designer. Do not modify.
namespace Frontend
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action mediaPlayAction;
		
		private global::Gtk.Action mediaStopAction;
		
		private global::Gtk.Action saveAsAction;
		
		private global::Gtk.Action saveAction;
		
		private global::Gtk.Action openAction;
		
		private global::Gtk.Action refreshAction;
		
		private global::Gtk.Action quitAction;
		
		private global::Gtk.Action aboutAction;
		
		private global::Gtk.Action preferencesAction;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.MenuBar menubarMain;
		
		private global::Gtk.Toolbar toolbarMain;
		
		private global::Gtk.HPaned hpanedMain;
		
		private global::Gtk.VBox vbox5;
		
		private global::Gtk.DrawingArea drawingareaMCU;
		
		private global::Gtk.Frame frame5;
		
		private global::Gtk.Alignment GtkAlignment21;
		
		private global::Gtk.VBox vbox9;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Label label14;
		
		private global::Gtk.ComboBox cbBoardType;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.Label label15;
		
		private global::Gtk.ComboBox cbAREF;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.Label label16;
		
		private global::Gtk.SpinButton sbAREFExternal;
		
		private global::Gtk.Label label17;
		
		private global::Gtk.Label GtkLabel8;
		
		private global::Gtk.Notebook notebook1;
		
		private global::Gtk.Table table1;
		
		private global::Gtk.Frame frame3;
		
		private global::Gtk.Alignment GtkAlignment6;
		
		private global::Gtk.Table table3;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow3;
		
		private global::Gtk.NodeView nvAnalogPins;
		
		private global::Gtk.VBox vbox8;
		
		private global::Gtk.Button btnAddAPin;
		
		private global::Gtk.Button btnCloneAPin;
		
		private global::Gtk.Button btnEditAPin;
		
		private global::Gtk.Button btnRemoveAPin;
		
		private global::Gtk.Button btnClearAPins;
		
		private global::Gtk.Label GtkLabel21;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment19;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.Button btnAddSignal;
		
		private global::Gtk.Button btnCloneSignal;
		
		private global::Gtk.Button btnEditSignal;
		
		private global::Gtk.Button btnRemoveSignal;
		
		private global::Gtk.Button btnClearSignals;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.NodeView nvMeasurementCombinations;
		
		private global::Gtk.Label GtkLabel34;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.VBox vbox7;
		
		private global::Gtk.Frame frame4;
		
		private global::Gtk.Alignment GtkAlignment17;
		
		private global::Gtk.Table table4;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		
		private global::Gtk.NodeView nvDigitalPins;
		
		private global::Gtk.VBox vbox10;
		
		private global::Gtk.Button btnAddDPin;
		
		private global::Gtk.Button btnCloneDPin;
		
		private global::Gtk.Button btnEditDPin;
		
		private global::Gtk.Button btnRemoveDPin;
		
		private global::Gtk.Button btnClearDPins;
		
		private global::Gtk.Label GtkLabel25;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Frame fSequences;
		
		private global::Gtk.Alignment GtkAlignment25;
		
		private global::Gtk.VPaned vpanedSequences;
		
		private global::Gtk.HBox hbSequences;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.Button btnAddSequence;
		
		private global::Gtk.Button btnCloneSequence;
		
		private global::Gtk.Button btnEditSequence;
		
		private global::Gtk.Button btnRemoveSequence;
		
		private global::Gtk.Button btnClearSequence;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow4;
		
		private global::Gtk.NodeView nvSequences;
		
		private global::Gtk.Label GtkLabel35;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.VBox vboxSettings;
		
		private global::Gtk.Frame frameCSVLoggerSettings;
		
		private global::Gtk.Alignment GtkAlignment31;
		
		private global::Gtk.Table tableCSVLoggerSettings;
		
		private global::Gtk.Button btnCSVFilePathOpen;
		
		private global::Gtk.CheckButton cbCSVUTC;
		
		private global::Gtk.ComboBoxEntry cbeCSVSeparator;
		
		private global::Gtk.ComboBox cbeCSVTimeFormat;
		
		private global::Gtk.Entry eCSVFilePath;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.ComboBoxEntry cbeFileNaming1;
		
		private global::Gtk.Label label24;
		
		private global::Gtk.ComboBoxEntry cbeFileNaming2;
		
		private global::Gtk.Label label25;
		
		private global::Gtk.ComboBoxEntry cbeFileNaming3;
		
		private global::Gtk.HSeparator hseparator2;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.Label label18;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label label20;
		
		private global::Gtk.Label label22;
		
		private global::Gtk.Label label23;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Label lblPreviewFilePathFormat;
		
		private global::Gtk.Label GtkLabel41;
		
		private global::Gtk.HSeparator hseparator1;
		
		private global::Gtk.Button btnCSVOpenFolder;
		
		private global::Gtk.HSeparator hseparator3;
		
		private global::Gtk.Frame frameRealTimePlotSettings;
		
		private global::Gtk.Alignment GtkAlignment33;
		
		private global::Gtk.Table tableRealTimePlotSettings;
		
		private global::Gtk.CheckButton cbPlotUseMarkers;
		
		private global::Gtk.Label label26;
		
		private global::Gtk.Label label27;
		
		private global::Gtk.SpinButton sbtnMaxValueCountPlot;
		
		private global::Gtk.Label GtkLabel42;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.VBox vboxRealTimePlot;
		
		private global::Gtk.Table table5;
		
		private global::Gtk.Button button122;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.Table table2;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView tvLog;
		
		private global::Gtk.VButtonBox vbuttonbox1;
		
		private global::Gtk.Button btnDigitalPingTest;
		
		private global::Gtk.Button btnFillAnalogInputs;
		
		private global::Gtk.Button btnFillDigitalOutputs;
		
		private global::Gtk.Button btnFillSequences;
		
		private global::Gtk.Button btnFillSignals;
		
		private global::Gtk.Button btnAlternateBlinkSetup;
		
		private global::Gtk.Button btnAlternateBlinkSetup2;
		
		private global::Gtk.Button button359;
		
		private global::Gtk.Button button360;
		
		private global::Gtk.Button button1125;
		
		private global::Gtk.Button btnBoardDifferenceTest;
		
		private global::Gtk.Button btnRefreshNV;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.Statusbar statusbar1;
		
		private global::Gtk.Image ImageConnectionStatus;
		
		private global::Gtk.Label lblConnectionStatus;
		
		private global::Gtk.VSeparator vseparator1;
		
		private global::Gtk.Label label12;
		
		private global::Gtk.Label lblStartTime;
		
		private global::Gtk.VSeparator vseparator2;
		
		private global::Gtk.Label label13;
		
		private global::Gtk.Label lblTimePassed;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Frontend.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.mediaPlayAction = new global::Gtk.Action ("mediaPlayAction", global::Mono.Unix.Catalog.GetString ("Start"), global::Mono.Unix.Catalog.GetString ("Start measurements and sequences"), "gtk-media-play");
			this.mediaPlayAction.Sensitive = false;
			this.mediaPlayAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Start");
			w1.Add (this.mediaPlayAction, null);
			this.mediaStopAction = new global::Gtk.Action ("mediaStopAction", null, global::Mono.Unix.Catalog.GetString ("Stops measurements and sequences"), "gtk-media-stop");
			this.mediaStopAction.Sensitive = false;
			w1.Add (this.mediaStopAction, null);
			this.saveAsAction = new global::Gtk.Action ("saveAsAction", null, global::Mono.Unix.Catalog.GetString ("Saves a configuration to a defined file"), "gtk-save-as");
			w1.Add (this.saveAsAction, null);
			this.saveAction = new global::Gtk.Action ("saveAction", null, global::Mono.Unix.Catalog.GetString ("Saves a configuration"), "gtk-save");
			w1.Add (this.saveAction, null);
			this.openAction = new global::Gtk.Action ("openAction", null, global::Mono.Unix.Catalog.GetString ("Opens a selected configuration"), "gtk-open");
			w1.Add (this.openAction, null);
			this.refreshAction = new global::Gtk.Action ("refreshAction", global::Mono.Unix.Catalog.GetString ("Attempt autoconnect"), global::Mono.Unix.Catalog.GetString ("attempts a automatic connection to a prepared microcontroller"), "gtk-refresh");
			this.refreshAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Autoconnect");
			w1.Add (this.refreshAction, null);
			this.quitAction = new global::Gtk.Action ("quitAction", global::Mono.Unix.Catalog.GetString ("_Quit"), null, "gtk-quit");
			this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Quit");
			w1.Add (this.quitAction, null);
			this.aboutAction = new global::Gtk.Action ("aboutAction", global::Mono.Unix.Catalog.GetString ("_About"), null, "gtk-about");
			this.aboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_About");
			w1.Add (this.aboutAction, null);
			this.preferencesAction = new global::Gtk.Action ("preferencesAction", global::Mono.Unix.Catalog.GetString ("_Preferences"), null, "gtk-preferences");
			this.preferencesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Preferences");
			w1.Add (this.preferencesAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.WidthRequest = 800;
			this.HeightRequest = 600;
			this.Name = "Frontend.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			// Container child Frontend.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubarMain'/></ui>");
			this.menubarMain = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubarMain")));
			this.menubarMain.Name = "menubarMain";
			this.vbox1.Add (this.menubarMain);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubarMain]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='toolbarMain'><toolitem name='openAction' action='openAction'/><toolitem name='saveAction' action='saveAction'/><toolitem name='saveAsAction' action='saveAsAction'/><separator/><toolitem name='refreshAction' action='refreshAction'/><separator/><toolitem name='mediaPlayAction' action='mediaPlayAction'/><toolitem name='mediaStopAction' action='mediaStopAction'/></toolbar></ui>");
			this.toolbarMain = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbarMain")));
			this.toolbarMain.Name = "toolbarMain";
			this.toolbarMain.ShowArrow = false;
			this.toolbarMain.ToolbarStyle = ((global::Gtk.ToolbarStyle)(2));
			this.toolbarMain.IconSize = ((global::Gtk.IconSize)(4));
			this.vbox1.Add (this.toolbarMain);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.toolbarMain]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hpanedMain = new global::Gtk.HPaned ();
			this.hpanedMain.CanFocus = true;
			this.hpanedMain.Name = "hpanedMain";
			this.hpanedMain.Position = 293;
			// Container child hpanedMain.Gtk.Paned+PanedChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.drawingareaMCU = new global::Gtk.DrawingArea ();
			this.drawingareaMCU.Name = "drawingareaMCU";
			this.vbox5.Add (this.drawingareaMCU);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.drawingareaMCU]));
			w4.Position = 0;
			// Container child vbox5.Gtk.Box+BoxChild
			this.frame5 = new global::Gtk.Frame ();
			this.frame5.Name = "frame5";
			this.frame5.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame5.Gtk.Container+ContainerChild
			this.GtkAlignment21 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment21.Name = "GtkAlignment21";
			this.GtkAlignment21.LeftPadding = ((uint)(5));
			this.GtkAlignment21.RightPadding = ((uint)(5));
			this.GtkAlignment21.BottomPadding = ((uint)(5));
			// Container child GtkAlignment21.Gtk.Container+ContainerChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.Xalign = 0F;
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Boardtype:");
			this.hbox6.Add (this.label14);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label14]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.cbBoardType = global::Gtk.ComboBox.NewText ();
			this.cbBoardType.Name = "cbBoardType";
			this.hbox6.Add (this.cbBoardType);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.cbBoardType]));
			w6.Position = 1;
			this.vbox9.Add (this.hbox6);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hbox6]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.Xalign = 0F;
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Analogreference Voltage Source:");
			this.hbox7.Add (this.label15);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label15]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.cbAREF = global::Gtk.ComboBox.NewText ();
			this.cbAREF.Name = "cbAREF";
			this.hbox7.Add (this.cbAREF);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.cbAREF]));
			w9.Position = 1;
			this.vbox9.Add (this.hbox7);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hbox7]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.Xalign = 0F;
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("External Analogreference Voltage;");
			this.hbox8.Add (this.label16);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label16]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.sbAREFExternal = new global::Gtk.SpinButton (0, 100, 1);
			this.sbAREFExternal.CanFocus = true;
			this.sbAREFExternal.Name = "sbAREFExternal";
			this.sbAREFExternal.Adjustment.PageIncrement = 10;
			this.sbAREFExternal.ClimbRate = 1;
			this.sbAREFExternal.Digits = ((uint)(2));
			this.sbAREFExternal.Numeric = true;
			this.hbox8.Add (this.sbAREFExternal);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.sbAREFExternal]));
			w12.Position = 1;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("V");
			this.hbox8.Add (this.label17);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label17]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			this.vbox9.Add (this.hbox8);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hbox8]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			this.GtkAlignment21.Add (this.vbox9);
			this.frame5.Add (this.GtkAlignment21);
			this.GtkLabel8 = new global::Gtk.Label ();
			this.GtkLabel8.Name = "GtkLabel8";
			this.GtkLabel8.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Board Properties</b>");
			this.GtkLabel8.UseMarkup = true;
			this.frame5.LabelWidget = this.GtkLabel8;
			this.vbox5.Add (this.frame5);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.frame5]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			this.hpanedMain.Add (this.vbox5);
			global::Gtk.Paned.PanedChild w18 = ((global::Gtk.Paned.PanedChild)(this.hpanedMain [this.vbox5]));
			w18.Resize = false;
			// Container child hpanedMain.Gtk.Paned+PanedChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.table1 = new global::Gtk.Table (((uint)(1)), ((uint)(1)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment6 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment6.Name = "GtkAlignment6";
			this.GtkAlignment6.LeftPadding = ((uint)(12));
			// Container child GtkAlignment6.Gtk.Container+ContainerChild
			this.table3 = new global::Gtk.Table (((uint)(1)), ((uint)(2)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
			this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
			this.nvAnalogPins = new global::Gtk.NodeView ();
			this.nvAnalogPins.CanFocus = true;
			this.nvAnalogPins.Name = "nvAnalogPins";
			this.nvAnalogPins.Reorderable = true;
			this.nvAnalogPins.SearchColumn = 1;
			this.nvAnalogPins.HoverExpand = true;
			this.GtkScrolledWindow3.Add (this.nvAnalogPins);
			this.table3.Add (this.GtkScrolledWindow3);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table3 [this.GtkScrolledWindow3]));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			// Container child table3.Gtk.Table+TableChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.WidthRequest = 165;
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.btnAddAPin = new global::Gtk.Button ();
			this.btnAddAPin.HeightRequest = 26;
			this.btnAddAPin.CanFocus = true;
			this.btnAddAPin.Name = "btnAddAPin";
			this.btnAddAPin.UseUnderline = true;
			this.btnAddAPin.Label = global::Mono.Unix.Catalog.GetString ("Add Measurement...");
			global::Gtk.Image w21 = new global::Gtk.Image ();
			w21.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			this.btnAddAPin.Image = w21;
			this.vbox8.Add (this.btnAddAPin);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.btnAddAPin]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.btnCloneAPin = new global::Gtk.Button ();
			this.btnCloneAPin.HeightRequest = 26;
			this.btnCloneAPin.CanFocus = true;
			this.btnCloneAPin.Name = "btnCloneAPin";
			this.btnCloneAPin.UseUnderline = true;
			this.btnCloneAPin.Label = global::Mono.Unix.Catalog.GetString ("Duplicate");
			global::Gtk.Image w23 = new global::Gtk.Image ();
			w23.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-copy", global::Gtk.IconSize.Menu);
			this.btnCloneAPin.Image = w23;
			this.vbox8.Add (this.btnCloneAPin);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.btnCloneAPin]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.btnEditAPin = new global::Gtk.Button ();
			this.btnEditAPin.CanFocus = true;
			this.btnEditAPin.Name = "btnEditAPin";
			this.btnEditAPin.UseUnderline = true;
			this.btnEditAPin.Label = global::Mono.Unix.Catalog.GetString ("Edit Measurement...");
			global::Gtk.Image w25 = new global::Gtk.Image ();
			w25.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Menu);
			this.btnEditAPin.Image = w25;
			this.vbox8.Add (this.btnEditAPin);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.btnEditAPin]));
			w26.Position = 2;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.btnRemoveAPin = new global::Gtk.Button ();
			this.btnRemoveAPin.HeightRequest = 26;
			this.btnRemoveAPin.CanFocus = true;
			this.btnRemoveAPin.Name = "btnRemoveAPin";
			this.btnRemoveAPin.UseUnderline = true;
			this.btnRemoveAPin.Label = global::Mono.Unix.Catalog.GetString ("Delete Measurement");
			global::Gtk.Image w27 = new global::Gtk.Image ();
			w27.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
			this.btnRemoveAPin.Image = w27;
			this.vbox8.Add (this.btnRemoveAPin);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.btnRemoveAPin]));
			w28.Position = 3;
			w28.Expand = false;
			w28.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.btnClearAPins = new global::Gtk.Button ();
			this.btnClearAPins.HeightRequest = 26;
			this.btnClearAPins.CanFocus = true;
			this.btnClearAPins.Name = "btnClearAPins";
			this.btnClearAPins.UseUnderline = true;
			this.btnClearAPins.Label = global::Mono.Unix.Catalog.GetString ("Clear");
			global::Gtk.Image w29 = new global::Gtk.Image ();
			w29.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-clear", global::Gtk.IconSize.Menu);
			this.btnClearAPins.Image = w29;
			this.vbox8.Add (this.btnClearAPins);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.btnClearAPins]));
			w30.Position = 4;
			w30.Expand = false;
			w30.Fill = false;
			this.table3.Add (this.vbox8);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table3 [this.vbox8]));
			w31.XOptions = ((global::Gtk.AttachOptions)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment6.Add (this.table3);
			this.frame3.Add (this.GtkAlignment6);
			this.GtkLabel21 = new global::Gtk.Label ();
			this.GtkLabel21.Name = "GtkLabel21";
			this.GtkLabel21.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Measurements</b>");
			this.GtkLabel21.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel21;
			this.table1.Add (this.frame3);
			this.notebook1.Add (this.table1);
			// Notebook tab
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Measurements");
			this.notebook1.SetTabLabel (this.table1, this.label6);
			this.label6.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment19 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment19.Name = "GtkAlignment19";
			this.GtkAlignment19.LeftPadding = ((uint)(12));
			// Container child GtkAlignment19.Gtk.Container+ContainerChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.WidthRequest = 165;
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.btnAddSignal = new global::Gtk.Button ();
			this.btnAddSignal.HeightRequest = 26;
			this.btnAddSignal.CanFocus = true;
			this.btnAddSignal.Name = "btnAddSignal";
			this.btnAddSignal.UseUnderline = true;
			this.btnAddSignal.Label = global::Mono.Unix.Catalog.GetString ("Add Combination...");
			global::Gtk.Image w36 = new global::Gtk.Image ();
			w36.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			this.btnAddSignal.Image = w36;
			this.vbox4.Add (this.btnAddSignal);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.btnAddSignal]));
			w37.Position = 0;
			w37.Expand = false;
			w37.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.btnCloneSignal = new global::Gtk.Button ();
			this.btnCloneSignal.HeightRequest = 26;
			this.btnCloneSignal.CanFocus = true;
			this.btnCloneSignal.Name = "btnCloneSignal";
			this.btnCloneSignal.UseUnderline = true;
			this.btnCloneSignal.Label = global::Mono.Unix.Catalog.GetString ("Duplicate");
			global::Gtk.Image w38 = new global::Gtk.Image ();
			w38.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-copy", global::Gtk.IconSize.Menu);
			this.btnCloneSignal.Image = w38;
			this.vbox4.Add (this.btnCloneSignal);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.btnCloneSignal]));
			w39.Position = 1;
			w39.Expand = false;
			w39.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.btnEditSignal = new global::Gtk.Button ();
			this.btnEditSignal.CanFocus = true;
			this.btnEditSignal.Name = "btnEditSignal";
			this.btnEditSignal.UseUnderline = true;
			this.btnEditSignal.Label = global::Mono.Unix.Catalog.GetString ("Edit Combination...");
			global::Gtk.Image w40 = new global::Gtk.Image ();
			w40.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Menu);
			this.btnEditSignal.Image = w40;
			this.vbox4.Add (this.btnEditSignal);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.btnEditSignal]));
			w41.Position = 2;
			w41.Expand = false;
			w41.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.btnRemoveSignal = new global::Gtk.Button ();
			this.btnRemoveSignal.HeightRequest = 26;
			this.btnRemoveSignal.CanFocus = true;
			this.btnRemoveSignal.Name = "btnRemoveSignal";
			this.btnRemoveSignal.UseUnderline = true;
			this.btnRemoveSignal.Label = global::Mono.Unix.Catalog.GetString ("Delete Combination");
			global::Gtk.Image w42 = new global::Gtk.Image ();
			w42.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
			this.btnRemoveSignal.Image = w42;
			this.vbox4.Add (this.btnRemoveSignal);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.btnRemoveSignal]));
			w43.Position = 3;
			w43.Expand = false;
			w43.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.btnClearSignals = new global::Gtk.Button ();
			this.btnClearSignals.HeightRequest = 26;
			this.btnClearSignals.CanFocus = true;
			this.btnClearSignals.Name = "btnClearSignals";
			this.btnClearSignals.UseUnderline = true;
			this.btnClearSignals.Label = global::Mono.Unix.Catalog.GetString ("Clear");
			global::Gtk.Image w44 = new global::Gtk.Image ();
			w44.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-clear", global::Gtk.IconSize.Menu);
			this.btnClearSignals.Image = w44;
			this.vbox4.Add (this.btnClearSignals);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.btnClearSignals]));
			w45.Position = 4;
			w45.Expand = false;
			w45.Fill = false;
			this.hbox5.Add (this.vbox4);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.vbox4]));
			w46.Position = 0;
			w46.Expand = false;
			w46.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.nvMeasurementCombinations = new global::Gtk.NodeView ();
			this.nvMeasurementCombinations.CanFocus = true;
			this.nvMeasurementCombinations.Name = "nvMeasurementCombinations";
			this.GtkScrolledWindow1.Add (this.nvMeasurementCombinations);
			this.hbox5.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.GtkScrolledWindow1]));
			w48.Position = 1;
			this.GtkAlignment19.Add (this.hbox5);
			this.frame1.Add (this.GtkAlignment19);
			this.GtkLabel34 = new global::Gtk.Label ();
			this.GtkLabel34.Name = "GtkLabel34";
			this.GtkLabel34.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Measurement Combinations</b>");
			this.GtkLabel34.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel34;
			this.notebook1.Add (this.frame1);
			global::Gtk.Notebook.NotebookChild w51 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.frame1]));
			w51.Position = 1;
			w51.MenuLabel = "";
			// Notebook tab
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Measurement Combinations");
			this.notebook1.SetTabLabel (this.frame1, this.label7);
			this.label7.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.frame4 = new global::Gtk.Frame ();
			this.frame4.Name = "frame4";
			this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame4.Gtk.Container+ContainerChild
			this.GtkAlignment17 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment17.Name = "GtkAlignment17";
			this.GtkAlignment17.LeftPadding = ((uint)(12));
			// Container child GtkAlignment17.Gtk.Container+ContainerChild
			this.table4 = new global::Gtk.Table (((uint)(1)), ((uint)(2)), false);
			this.table4.Name = "table4";
			this.table4.RowSpacing = ((uint)(6));
			this.table4.ColumnSpacing = ((uint)(6));
			// Container child table4.Gtk.Table+TableChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.nvDigitalPins = new global::Gtk.NodeView ();
			this.nvDigitalPins.CanFocus = true;
			this.nvDigitalPins.Name = "nvDigitalPins";
			this.GtkScrolledWindow2.Add (this.nvDigitalPins);
			this.table4.Add (this.GtkScrolledWindow2);
			global::Gtk.Table.TableChild w53 = ((global::Gtk.Table.TableChild)(this.table4 [this.GtkScrolledWindow2]));
			w53.LeftAttach = ((uint)(1));
			w53.RightAttach = ((uint)(2));
			// Container child table4.Gtk.Table+TableChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.WidthRequest = 165;
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.btnAddDPin = new global::Gtk.Button ();
			this.btnAddDPin.HeightRequest = 26;
			this.btnAddDPin.CanFocus = true;
			this.btnAddDPin.Name = "btnAddDPin";
			this.btnAddDPin.UseUnderline = true;
			this.btnAddDPin.Label = global::Mono.Unix.Catalog.GetString ("Add digital Output...");
			global::Gtk.Image w54 = new global::Gtk.Image ();
			w54.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			this.btnAddDPin.Image = w54;
			this.vbox10.Add (this.btnAddDPin);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.btnAddDPin]));
			w55.Position = 0;
			w55.Expand = false;
			w55.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.btnCloneDPin = new global::Gtk.Button ();
			this.btnCloneDPin.HeightRequest = 26;
			this.btnCloneDPin.CanFocus = true;
			this.btnCloneDPin.Name = "btnCloneDPin";
			this.btnCloneDPin.UseUnderline = true;
			this.btnCloneDPin.Label = global::Mono.Unix.Catalog.GetString ("Duplicate");
			global::Gtk.Image w56 = new global::Gtk.Image ();
			w56.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-copy", global::Gtk.IconSize.Menu);
			this.btnCloneDPin.Image = w56;
			this.vbox10.Add (this.btnCloneDPin);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.btnCloneDPin]));
			w57.Position = 1;
			w57.Expand = false;
			w57.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.btnEditDPin = new global::Gtk.Button ();
			this.btnEditDPin.CanFocus = true;
			this.btnEditDPin.Name = "btnEditDPin";
			this.btnEditDPin.UseUnderline = true;
			this.btnEditDPin.Label = global::Mono.Unix.Catalog.GetString ("Edit digital Output...");
			global::Gtk.Image w58 = new global::Gtk.Image ();
			w58.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Menu);
			this.btnEditDPin.Image = w58;
			this.vbox10.Add (this.btnEditDPin);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.btnEditDPin]));
			w59.Position = 2;
			w59.Expand = false;
			w59.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.btnRemoveDPin = new global::Gtk.Button ();
			this.btnRemoveDPin.HeightRequest = 26;
			this.btnRemoveDPin.CanFocus = true;
			this.btnRemoveDPin.Name = "btnRemoveDPin";
			this.btnRemoveDPin.UseUnderline = true;
			this.btnRemoveDPin.Label = global::Mono.Unix.Catalog.GetString ("Delete digital Output");
			global::Gtk.Image w60 = new global::Gtk.Image ();
			w60.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
			this.btnRemoveDPin.Image = w60;
			this.vbox10.Add (this.btnRemoveDPin);
			global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.btnRemoveDPin]));
			w61.Position = 3;
			w61.Expand = false;
			w61.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.btnClearDPins = new global::Gtk.Button ();
			this.btnClearDPins.HeightRequest = 26;
			this.btnClearDPins.CanFocus = true;
			this.btnClearDPins.Name = "btnClearDPins";
			this.btnClearDPins.UseUnderline = true;
			this.btnClearDPins.Label = global::Mono.Unix.Catalog.GetString ("Clear");
			global::Gtk.Image w62 = new global::Gtk.Image ();
			w62.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-clear", global::Gtk.IconSize.Menu);
			this.btnClearDPins.Image = w62;
			this.vbox10.Add (this.btnClearDPins);
			global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.btnClearDPins]));
			w63.Position = 4;
			w63.Expand = false;
			w63.Fill = false;
			this.table4.Add (this.vbox10);
			global::Gtk.Table.TableChild w64 = ((global::Gtk.Table.TableChild)(this.table4 [this.vbox10]));
			w64.XOptions = ((global::Gtk.AttachOptions)(4));
			w64.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment17.Add (this.table4);
			this.frame4.Add (this.GtkAlignment17);
			this.GtkLabel25 = new global::Gtk.Label ();
			this.GtkLabel25.Name = "GtkLabel25";
			this.GtkLabel25.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Digital Outputs</b>");
			this.GtkLabel25.UseMarkup = true;
			this.frame4.LabelWidget = this.GtkLabel25;
			this.vbox7.Add (this.frame4);
			global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.frame4]));
			w67.Position = 0;
			this.notebook1.Add (this.vbox7);
			global::Gtk.Notebook.NotebookChild w68 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox7]));
			w68.Position = 2;
			// Notebook tab
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Output");
			this.notebook1.SetTabLabel (this.vbox7, this.label5);
			this.label5.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.fSequences = new global::Gtk.Frame ();
			this.fSequences.Name = "fSequences";
			this.fSequences.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child fSequences.Gtk.Container+ContainerChild
			this.GtkAlignment25 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment25.Name = "GtkAlignment25";
			this.GtkAlignment25.LeftPadding = ((uint)(12));
			// Container child GtkAlignment25.Gtk.Container+ContainerChild
			this.vpanedSequences = new global::Gtk.VPaned ();
			this.vpanedSequences.CanFocus = true;
			this.vpanedSequences.Name = "vpanedSequences";
			this.vpanedSequences.Position = 1;
			// Container child vpanedSequences.Gtk.Paned+PanedChild
			this.hbSequences = new global::Gtk.HBox ();
			this.hbSequences.Name = "hbSequences";
			this.hbSequences.Spacing = 6;
			// Container child hbSequences.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.WidthRequest = 165;
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.btnAddSequence = new global::Gtk.Button ();
			this.btnAddSequence.HeightRequest = 26;
			this.btnAddSequence.CanFocus = true;
			this.btnAddSequence.Name = "btnAddSequence";
			this.btnAddSequence.UseUnderline = true;
			this.btnAddSequence.Label = global::Mono.Unix.Catalog.GetString ("Add Sequence...");
			global::Gtk.Image w69 = new global::Gtk.Image ();
			w69.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			this.btnAddSequence.Image = w69;
			this.vbox3.Add (this.btnAddSequence);
			global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.btnAddSequence]));
			w70.Position = 0;
			w70.Expand = false;
			w70.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.btnCloneSequence = new global::Gtk.Button ();
			this.btnCloneSequence.HeightRequest = 26;
			this.btnCloneSequence.CanFocus = true;
			this.btnCloneSequence.Name = "btnCloneSequence";
			this.btnCloneSequence.UseUnderline = true;
			this.btnCloneSequence.Label = global::Mono.Unix.Catalog.GetString ("Duplicate");
			global::Gtk.Image w71 = new global::Gtk.Image ();
			w71.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-copy", global::Gtk.IconSize.Menu);
			this.btnCloneSequence.Image = w71;
			this.vbox3.Add (this.btnCloneSequence);
			global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.btnCloneSequence]));
			w72.Position = 1;
			w72.Expand = false;
			w72.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.btnEditSequence = new global::Gtk.Button ();
			this.btnEditSequence.CanFocus = true;
			this.btnEditSequence.Name = "btnEditSequence";
			this.btnEditSequence.UseUnderline = true;
			this.btnEditSequence.Label = global::Mono.Unix.Catalog.GetString ("Edit Sequence...");
			global::Gtk.Image w73 = new global::Gtk.Image ();
			w73.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Menu);
			this.btnEditSequence.Image = w73;
			this.vbox3.Add (this.btnEditSequence);
			global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.btnEditSequence]));
			w74.Position = 2;
			w74.Expand = false;
			w74.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.btnRemoveSequence = new global::Gtk.Button ();
			this.btnRemoveSequence.HeightRequest = 26;
			this.btnRemoveSequence.CanFocus = true;
			this.btnRemoveSequence.Name = "btnRemoveSequence";
			this.btnRemoveSequence.UseUnderline = true;
			this.btnRemoveSequence.Label = global::Mono.Unix.Catalog.GetString ("Delete Sequence");
			global::Gtk.Image w75 = new global::Gtk.Image ();
			w75.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
			this.btnRemoveSequence.Image = w75;
			this.vbox3.Add (this.btnRemoveSequence);
			global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.btnRemoveSequence]));
			w76.Position = 3;
			w76.Expand = false;
			w76.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.btnClearSequence = new global::Gtk.Button ();
			this.btnClearSequence.HeightRequest = 26;
			this.btnClearSequence.CanFocus = true;
			this.btnClearSequence.Name = "btnClearSequence";
			this.btnClearSequence.UseUnderline = true;
			this.btnClearSequence.Label = global::Mono.Unix.Catalog.GetString ("Clear");
			global::Gtk.Image w77 = new global::Gtk.Image ();
			w77.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-clear", global::Gtk.IconSize.Menu);
			this.btnClearSequence.Image = w77;
			this.vbox3.Add (this.btnClearSequence);
			global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.btnClearSequence]));
			w78.Position = 4;
			w78.Expand = false;
			w78.Fill = false;
			this.hbSequences.Add (this.vbox3);
			global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.hbSequences [this.vbox3]));
			w79.Position = 0;
			w79.Expand = false;
			w79.Fill = false;
			// Container child hbSequences.Gtk.Box+BoxChild
			this.GtkScrolledWindow4 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow4.Name = "GtkScrolledWindow4";
			this.GtkScrolledWindow4.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow4.Gtk.Container+ContainerChild
			this.nvSequences = new global::Gtk.NodeView ();
			this.nvSequences.CanFocus = true;
			this.nvSequences.Name = "nvSequences";
			this.nvSequences.Reorderable = true;
			this.GtkScrolledWindow4.Add (this.nvSequences);
			this.hbSequences.Add (this.GtkScrolledWindow4);
			global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.hbSequences [this.GtkScrolledWindow4]));
			w81.Position = 1;
			this.vpanedSequences.Add (this.hbSequences);
			global::Gtk.Paned.PanedChild w82 = ((global::Gtk.Paned.PanedChild)(this.vpanedSequences [this.hbSequences]));
			w82.Resize = false;
			this.GtkAlignment25.Add (this.vpanedSequences);
			this.fSequences.Add (this.GtkAlignment25);
			this.GtkLabel35 = new global::Gtk.Label ();
			this.GtkLabel35.Name = "GtkLabel35";
			this.GtkLabel35.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Digital Sequences</b>");
			this.GtkLabel35.UseMarkup = true;
			this.fSequences.LabelWidget = this.GtkLabel35;
			this.notebook1.Add (this.fSequences);
			global::Gtk.Notebook.NotebookChild w85 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.fSequences]));
			w85.Position = 3;
			// Notebook tab
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Digital Sequences");
			this.notebook1.SetTabLabel (this.fSequences, this.label8);
			this.label8.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vboxSettings = new global::Gtk.VBox ();
			this.vboxSettings.Name = "vboxSettings";
			this.vboxSettings.Spacing = 6;
			// Container child vboxSettings.Gtk.Box+BoxChild
			this.frameCSVLoggerSettings = new global::Gtk.Frame ();
			this.frameCSVLoggerSettings.Name = "frameCSVLoggerSettings";
			this.frameCSVLoggerSettings.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frameCSVLoggerSettings.Gtk.Container+ContainerChild
			this.GtkAlignment31 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment31.Name = "GtkAlignment31";
			this.GtkAlignment31.LeftPadding = ((uint)(12));
			// Container child GtkAlignment31.Gtk.Container+ContainerChild
			this.tableCSVLoggerSettings = new global::Gtk.Table (((uint)(7)), ((uint)(3)), false);
			this.tableCSVLoggerSettings.Name = "tableCSVLoggerSettings";
			this.tableCSVLoggerSettings.RowSpacing = ((uint)(6));
			this.tableCSVLoggerSettings.ColumnSpacing = ((uint)(6));
			// Container child tableCSVLoggerSettings.Gtk.Table+TableChild
			this.btnCSVFilePathOpen = new global::Gtk.Button ();
			this.btnCSVFilePathOpen.CanFocus = true;
			this.btnCSVFilePathOpen.Name = "btnCSVFilePathOpen";
			this.btnCSVFilePathOpen.UseUnderline = true;
			global::Gtk.Image w86 = new global::Gtk.Image ();
			w86.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-open", global::Gtk.IconSize.Menu);
			this.btnCSVFilePathOpen.Image = w86;
			this.tableCSVLoggerSettings.Add (this.btnCSVFilePathOpen);
			global::Gtk.Table.TableChild w87 = ((global::Gtk.Table.TableChild)(this.tableCSVLoggerSettings [this.btnCSVFilePathOpen]));
			w87.TopAttach = ((uint)(1));
			w87.BottomAttach = ((uint)(2));
			w87.LeftAttach = ((uint)(2));
			w87.RightAttach = ((uint)(3));
			w87.XOptions = ((global::Gtk.AttachOptions)(0));
			w87.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child tableCSVLoggerSettings.Gtk.Table+TableChild
			this.cbCSVUTC = new global::Gtk.CheckButton ();
			this.cbCSVUTC.CanFocus = true;
			this.cbCSVUTC.Name = "cbCSVUTC";
			this.cbCSVUTC.Label = global::Mono.Unix.Catalog.GetString ("Append addtional UTC timestamp to csv log file");
			this.cbCSVUTC.DrawIndicator = true;
			this.cbCSVUTC.UseUnderline = true;
			this.tableCSVLoggerSettings.Add (this.cbCSVUTC);
			global::Gtk.Table.TableChild w88 = ((global::Gtk.Table.TableChild)(this.tableCSVLoggerSettings [this.cbCSVUTC]));
			w88.TopAttach = ((uint)(5));
			w88.BottomAttach = ((uint)(6));
			w88.LeftAttach = ((uint)(1));
			w88.RightAttach = ((uint)(3));
			w88.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableCSVLoggerSettings.Gtk.Table+TableChild
			this.cbeCSVSeparator = global::Gtk.ComboBoxEntry.NewText ();
			this.cbeCSVSeparator.Name = "cbeCSVSeparator";
			this.tableCSVLoggerSettings.Add (this.cbeCSVSeparator);
			global::Gtk.Table.TableChild w89 = ((global::Gtk.Table.TableChild)(this.tableCSVLoggerSettings [this.cbeCSVSeparator]));
			w89.TopAttach = ((uint)(4));
			w89.BottomAttach = ((uint)(5));
			w89.LeftAttach = ((uint)(1));
			w89.RightAttach = ((uint)(3));
			w89.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableCSVLoggerSettings.Gtk.Table+TableChild
			this.cbeCSVTimeFormat = global::Gtk.ComboBox.NewText ();
			this.cbeCSVTimeFormat.Name = "cbeCSVTimeFormat";
			this.tableCSVLoggerSettings.Add (this.cbeCSVTimeFormat);
			global::Gtk.Table.TableChild w90 = ((global::Gtk.Table.TableChild)(this.tableCSVLoggerSettings [this.cbeCSVTimeFormat]));
			w90.TopAttach = ((uint)(6));
			w90.BottomAttach = ((uint)(7));
			w90.LeftAttach = ((uint)(1));
			w90.RightAttach = ((uint)(3));
			w90.XOptions = ((global::Gtk.AttachOptions)(4));
			w90.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableCSVLoggerSettings.Gtk.Table+TableChild
			this.eCSVFilePath = new global::Gtk.Entry ();
			this.eCSVFilePath.CanFocus = true;
			this.eCSVFilePath.Name = "eCSVFilePath";
			this.eCSVFilePath.IsEditable = true;
			this.eCSVFilePath.InvisibleChar = '●';
			this.tableCSVLoggerSettings.Add (this.eCSVFilePath);
			global::Gtk.Table.TableChild w91 = ((global::Gtk.Table.TableChild)(this.tableCSVLoggerSettings [this.eCSVFilePath]));
			w91.TopAttach = ((uint)(1));
			w91.BottomAttach = ((uint)(2));
			w91.LeftAttach = ((uint)(1));
			w91.RightAttach = ((uint)(2));
			w91.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child tableCSVLoggerSettings.Gtk.Table+TableChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.cbeFileNaming1 = global::Gtk.ComboBoxEntry.NewText ();
			this.cbeFileNaming1.Name = "cbeFileNaming1";
			this.hbox1.Add (this.cbeFileNaming1);
			global::Gtk.Box.BoxChild w92 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.cbeFileNaming1]));
			w92.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label24 = new global::Gtk.Label ();
			this.label24.Name = "label24";
			this.label24.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>-</b>");
			this.label24.UseMarkup = true;
			this.hbox1.Add (this.label24);
			global::Gtk.Box.BoxChild w93 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label24]));
			w93.Position = 1;
			w93.Expand = false;
			w93.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.cbeFileNaming2 = global::Gtk.ComboBoxEntry.NewText ();
			this.cbeFileNaming2.Name = "cbeFileNaming2";
			this.hbox1.Add (this.cbeFileNaming2);
			global::Gtk.Box.BoxChild w94 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.cbeFileNaming2]));
			w94.Position = 2;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label25 = new global::Gtk.Label ();
			this.label25.Name = "label25";
			this.label25.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>-</b>");
			this.label25.UseMarkup = true;
			this.hbox1.Add (this.label25);
			global::Gtk.Box.BoxChild w95 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label25]));
			w95.Position = 3;
			w95.Expand = false;
			w95.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.cbeFileNaming3 = global::Gtk.ComboBoxEntry.NewText ();
			this.cbeFileNaming3.Name = "cbeFileNaming3";
			this.hbox1.Add (this.cbeFileNaming3);
			global::Gtk.Box.BoxChild w96 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.cbeFileNaming3]));
			w96.Position = 4;
			this.tableCSVLoggerSettings.Add (this.hbox1);
			global::Gtk.Table.TableChild w97 = ((global::Gtk.Table.TableChild)(this.tableCSVLoggerSettings [this.hbox1]));
			w97.LeftAttach = ((uint)(1));
			w97.RightAttach = ((uint)(2));
			w97.XOptions = ((global::Gtk.AttachOptions)(4));
			w97.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableCSVLoggerSettings.Gtk.Table+TableChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.tableCSVLoggerSettings.Add (this.hseparator2);
			global::Gtk.Table.TableChild w98 = ((global::Gtk.Table.TableChild)(this.tableCSVLoggerSettings [this.hseparator2]));
			w98.TopAttach = ((uint)(3));
			w98.BottomAttach = ((uint)(4));
			w98.RightAttach = ((uint)(3));
			w98.XOptions = ((global::Gtk.AttachOptions)(4));
			w98.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableCSVLoggerSettings.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.Xalign = 0F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Separator:");
			this.tableCSVLoggerSettings.Add (this.label11);
			global::Gtk.Table.TableChild w99 = ((global::Gtk.Table.TableChild)(this.tableCSVLoggerSettings [this.label11]));
			w99.TopAttach = ((uint)(4));
			w99.BottomAttach = ((uint)(5));
			w99.XOptions = ((global::Gtk.AttachOptions)(4));
			w99.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableCSVLoggerSettings.Gtk.Table+TableChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.Xalign = 0F;
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("File Path:");
			this.tableCSVLoggerSettings.Add (this.label18);
			global::Gtk.Table.TableChild w100 = ((global::Gtk.Table.TableChild)(this.tableCSVLoggerSettings [this.label18]));
			w100.TopAttach = ((uint)(1));
			w100.BottomAttach = ((uint)(2));
			w100.XOptions = ((global::Gtk.AttachOptions)(4));
			w100.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child tableCSVLoggerSettings.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("File Naming Convention:");
			this.tableCSVLoggerSettings.Add (this.label2);
			global::Gtk.Table.TableChild w101 = ((global::Gtk.Table.TableChild)(this.tableCSVLoggerSettings [this.label2]));
			w101.XOptions = ((global::Gtk.AttachOptions)(4));
			w101.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child tableCSVLoggerSettings.Gtk.Table+TableChild
			this.label20 = new global::Gtk.Label ();
			this.label20.Name = "label20";
			this.label20.Xalign = 0F;
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("UTC Timestamp:");
			this.tableCSVLoggerSettings.Add (this.label20);
			global::Gtk.Table.TableChild w102 = ((global::Gtk.Table.TableChild)(this.tableCSVLoggerSettings [this.label20]));
			w102.TopAttach = ((uint)(5));
			w102.BottomAttach = ((uint)(6));
			w102.XOptions = ((global::Gtk.AttachOptions)(4));
			w102.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableCSVLoggerSettings.Gtk.Table+TableChild
			this.label22 = new global::Gtk.Label ();
			this.label22.Name = "label22";
			this.label22.Xalign = 0F;
			this.label22.LabelProp = global::Mono.Unix.Catalog.GetString ("Time Format:");
			this.tableCSVLoggerSettings.Add (this.label22);
			global::Gtk.Table.TableChild w103 = ((global::Gtk.Table.TableChild)(this.tableCSVLoggerSettings [this.label22]));
			w103.TopAttach = ((uint)(6));
			w103.BottomAttach = ((uint)(7));
			w103.XOptions = ((global::Gtk.AttachOptions)(4));
			w103.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableCSVLoggerSettings.Gtk.Table+TableChild
			this.label23 = new global::Gtk.Label ();
			this.label23.Name = "label23";
			this.label23.Xalign = 0F;
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString ("Preview:");
			this.tableCSVLoggerSettings.Add (this.label23);
			global::Gtk.Table.TableChild w104 = ((global::Gtk.Table.TableChild)(this.tableCSVLoggerSettings [this.label23]));
			w104.TopAttach = ((uint)(2));
			w104.BottomAttach = ((uint)(3));
			w104.XOptions = ((global::Gtk.AttachOptions)(4));
			w104.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child tableCSVLoggerSettings.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString (".csv");
			this.tableCSVLoggerSettings.Add (this.label4);
			global::Gtk.Table.TableChild w105 = ((global::Gtk.Table.TableChild)(this.tableCSVLoggerSettings [this.label4]));
			w105.LeftAttach = ((uint)(2));
			w105.RightAttach = ((uint)(3));
			w105.XOptions = ((global::Gtk.AttachOptions)(0));
			w105.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child tableCSVLoggerSettings.Gtk.Table+TableChild
			this.lblPreviewFilePathFormat = new global::Gtk.Label ();
			this.lblPreviewFilePathFormat.Name = "lblPreviewFilePathFormat";
			this.lblPreviewFilePathFormat.Xalign = 0F;
			this.tableCSVLoggerSettings.Add (this.lblPreviewFilePathFormat);
			global::Gtk.Table.TableChild w106 = ((global::Gtk.Table.TableChild)(this.tableCSVLoggerSettings [this.lblPreviewFilePathFormat]));
			w106.TopAttach = ((uint)(2));
			w106.BottomAttach = ((uint)(3));
			w106.LeftAttach = ((uint)(1));
			w106.RightAttach = ((uint)(3));
			w106.YOptions = ((global::Gtk.AttachOptions)(0));
			this.GtkAlignment31.Add (this.tableCSVLoggerSettings);
			this.frameCSVLoggerSettings.Add (this.GtkAlignment31);
			this.GtkLabel41 = new global::Gtk.Label ();
			this.GtkLabel41.Name = "GtkLabel41";
			this.GtkLabel41.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>CSV Logger Settings</b>");
			this.GtkLabel41.UseMarkup = true;
			this.frameCSVLoggerSettings.LabelWidget = this.GtkLabel41;
			this.vboxSettings.Add (this.frameCSVLoggerSettings);
			global::Gtk.Box.BoxChild w109 = ((global::Gtk.Box.BoxChild)(this.vboxSettings [this.frameCSVLoggerSettings]));
			w109.Position = 0;
			w109.Expand = false;
			w109.Fill = false;
			// Container child vboxSettings.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vboxSettings.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w110 = ((global::Gtk.Box.BoxChild)(this.vboxSettings [this.hseparator1]));
			w110.Position = 1;
			w110.Expand = false;
			w110.Fill = false;
			// Container child vboxSettings.Gtk.Box+BoxChild
			this.btnCSVOpenFolder = new global::Gtk.Button ();
			this.btnCSVOpenFolder.CanFocus = true;
			this.btnCSVOpenFolder.Name = "btnCSVOpenFolder";
			this.btnCSVOpenFolder.UseUnderline = true;
			this.btnCSVOpenFolder.Label = global::Mono.Unix.Catalog.GetString ("Open CSV log file folder");
			global::Gtk.Image w111 = new global::Gtk.Image ();
			w111.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-open", global::Gtk.IconSize.Menu);
			this.btnCSVOpenFolder.Image = w111;
			this.vboxSettings.Add (this.btnCSVOpenFolder);
			global::Gtk.Box.BoxChild w112 = ((global::Gtk.Box.BoxChild)(this.vboxSettings [this.btnCSVOpenFolder]));
			w112.Position = 2;
			w112.Expand = false;
			w112.Fill = false;
			// Container child vboxSettings.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator ();
			this.hseparator3.Name = "hseparator3";
			this.vboxSettings.Add (this.hseparator3);
			global::Gtk.Box.BoxChild w113 = ((global::Gtk.Box.BoxChild)(this.vboxSettings [this.hseparator3]));
			w113.Position = 3;
			w113.Expand = false;
			w113.Fill = false;
			// Container child vboxSettings.Gtk.Box+BoxChild
			this.frameRealTimePlotSettings = new global::Gtk.Frame ();
			this.frameRealTimePlotSettings.Name = "frameRealTimePlotSettings";
			this.frameRealTimePlotSettings.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frameRealTimePlotSettings.Gtk.Container+ContainerChild
			this.GtkAlignment33 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment33.Name = "GtkAlignment33";
			this.GtkAlignment33.LeftPadding = ((uint)(12));
			// Container child GtkAlignment33.Gtk.Container+ContainerChild
			this.tableRealTimePlotSettings = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.tableRealTimePlotSettings.Name = "tableRealTimePlotSettings";
			this.tableRealTimePlotSettings.RowSpacing = ((uint)(6));
			this.tableRealTimePlotSettings.ColumnSpacing = ((uint)(6));
			// Container child tableRealTimePlotSettings.Gtk.Table+TableChild
			this.cbPlotUseMarkers = new global::Gtk.CheckButton ();
			this.cbPlotUseMarkers.CanFocus = true;
			this.cbPlotUseMarkers.Name = "cbPlotUseMarkers";
			this.cbPlotUseMarkers.Label = "";
			this.cbPlotUseMarkers.Active = true;
			this.cbPlotUseMarkers.DrawIndicator = true;
			this.cbPlotUseMarkers.UseUnderline = true;
			this.tableRealTimePlotSettings.Add (this.cbPlotUseMarkers);
			global::Gtk.Table.TableChild w114 = ((global::Gtk.Table.TableChild)(this.tableRealTimePlotSettings [this.cbPlotUseMarkers]));
			w114.LeftAttach = ((uint)(1));
			w114.RightAttach = ((uint)(3));
			w114.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableRealTimePlotSettings.Gtk.Table+TableChild
			this.label26 = new global::Gtk.Label ();
			this.label26.Name = "label26";
			this.label26.Xalign = 0F;
			this.label26.LabelProp = global::Mono.Unix.Catalog.GetString ("Use Markers:");
			this.tableRealTimePlotSettings.Add (this.label26);
			global::Gtk.Table.TableChild w115 = ((global::Gtk.Table.TableChild)(this.tableRealTimePlotSettings [this.label26]));
			w115.XOptions = ((global::Gtk.AttachOptions)(4));
			w115.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableRealTimePlotSettings.Gtk.Table+TableChild
			this.label27 = new global::Gtk.Label ();
			this.label27.Name = "label27";
			this.label27.LabelProp = global::Mono.Unix.Catalog.GetString ("Maximum Count of Values per Signal:");
			this.tableRealTimePlotSettings.Add (this.label27);
			global::Gtk.Table.TableChild w116 = ((global::Gtk.Table.TableChild)(this.tableRealTimePlotSettings [this.label27]));
			w116.TopAttach = ((uint)(1));
			w116.BottomAttach = ((uint)(2));
			w116.XOptions = ((global::Gtk.AttachOptions)(4));
			w116.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableRealTimePlotSettings.Gtk.Table+TableChild
			this.sbtnMaxValueCountPlot = new global::Gtk.SpinButton (1, 10000, 1);
			this.sbtnMaxValueCountPlot.CanFocus = true;
			this.sbtnMaxValueCountPlot.Name = "sbtnMaxValueCountPlot";
			this.sbtnMaxValueCountPlot.Adjustment.PageIncrement = 10;
			this.sbtnMaxValueCountPlot.ClimbRate = 1;
			this.sbtnMaxValueCountPlot.Numeric = true;
			this.sbtnMaxValueCountPlot.Value = 1000;
			this.tableRealTimePlotSettings.Add (this.sbtnMaxValueCountPlot);
			global::Gtk.Table.TableChild w117 = ((global::Gtk.Table.TableChild)(this.tableRealTimePlotSettings [this.sbtnMaxValueCountPlot]));
			w117.TopAttach = ((uint)(1));
			w117.BottomAttach = ((uint)(2));
			w117.LeftAttach = ((uint)(1));
			w117.RightAttach = ((uint)(3));
			w117.XOptions = ((global::Gtk.AttachOptions)(4));
			w117.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment33.Add (this.tableRealTimePlotSettings);
			this.frameRealTimePlotSettings.Add (this.GtkAlignment33);
			this.GtkLabel42 = new global::Gtk.Label ();
			this.GtkLabel42.Name = "GtkLabel42";
			this.GtkLabel42.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Real Time Plot Settings</b>");
			this.GtkLabel42.UseMarkup = true;
			this.frameRealTimePlotSettings.LabelWidget = this.GtkLabel42;
			this.vboxSettings.Add (this.frameRealTimePlotSettings);
			global::Gtk.Box.BoxChild w120 = ((global::Gtk.Box.BoxChild)(this.vboxSettings [this.frameRealTimePlotSettings]));
			w120.Position = 4;
			this.notebook1.Add (this.vboxSettings);
			global::Gtk.Notebook.NotebookChild w121 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vboxSettings]));
			w121.Position = 4;
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Settings");
			this.notebook1.SetTabLabel (this.vboxSettings, this.label1);
			this.label1.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vboxRealTimePlot = new global::Gtk.VBox ();
			this.vboxRealTimePlot.Name = "vboxRealTimePlot";
			this.vboxRealTimePlot.Spacing = 6;
			// Container child vboxRealTimePlot.Gtk.Box+BoxChild
			this.table5 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.table5.Name = "table5";
			this.table5.RowSpacing = ((uint)(6));
			this.table5.ColumnSpacing = ((uint)(6));
			// Container child table5.Gtk.Table+TableChild
			this.button122 = new global::Gtk.Button ();
			this.button122.CanFocus = true;
			this.button122.Name = "button122";
			this.button122.UseUnderline = true;
			this.button122.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.table5.Add (this.button122);
			global::Gtk.Table.TableChild w122 = ((global::Gtk.Table.TableChild)(this.table5 [this.button122]));
			w122.XOptions = ((global::Gtk.AttachOptions)(4));
			w122.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vboxRealTimePlot.Add (this.table5);
			global::Gtk.Box.BoxChild w123 = ((global::Gtk.Box.BoxChild)(this.vboxRealTimePlot [this.table5]));
			w123.Position = 1;
			this.notebook1.Add (this.vboxRealTimePlot);
			global::Gtk.Notebook.NotebookChild w124 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vboxRealTimePlot]));
			w124.Position = 5;
			// Notebook tab
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Real Time Plot");
			this.notebook1.SetTabLabel (this.vboxRealTimePlot, this.label9);
			this.label9.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.table2 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvLog = new global::Gtk.TextView ();
			this.tvLog.WidthRequest = 150;
			this.tvLog.CanFocus = true;
			this.tvLog.Name = "tvLog";
			this.GtkScrolledWindow.Add (this.tvLog);
			this.table2.Add (this.GtkScrolledWindow);
			global::Gtk.Table.TableChild w126 = ((global::Gtk.Table.TableChild)(this.table2 [this.GtkScrolledWindow]));
			w126.TopAttach = ((uint)(2));
			w126.BottomAttach = ((uint)(3));
			w126.RightAttach = ((uint)(3));
			// Container child table2.Gtk.Table+TableChild
			this.vbuttonbox1 = new global::Gtk.VButtonBox ();
			this.vbuttonbox1.Name = "vbuttonbox1";
			this.vbuttonbox1.Homogeneous = true;
			this.vbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnDigitalPingTest = new global::Gtk.Button ();
			this.btnDigitalPingTest.CanFocus = true;
			this.btnDigitalPingTest.Name = "btnDigitalPingTest";
			this.btnDigitalPingTest.UseUnderline = true;
			this.btnDigitalPingTest.Label = global::Mono.Unix.Catalog.GetString ("DigitalPingTest");
			this.vbuttonbox1.Add (this.btnDigitalPingTest);
			global::Gtk.ButtonBox.ButtonBoxChild w127 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.btnDigitalPingTest]));
			w127.Expand = false;
			w127.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnFillAnalogInputs = new global::Gtk.Button ();
			this.btnFillAnalogInputs.CanFocus = true;
			this.btnFillAnalogInputs.Name = "btnFillAnalogInputs";
			this.btnFillAnalogInputs.UseUnderline = true;
			this.btnFillAnalogInputs.Label = global::Mono.Unix.Catalog.GetString ("Fill Analog Inputs");
			this.vbuttonbox1.Add (this.btnFillAnalogInputs);
			global::Gtk.ButtonBox.ButtonBoxChild w128 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.btnFillAnalogInputs]));
			w128.Position = 1;
			w128.Expand = false;
			w128.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnFillDigitalOutputs = new global::Gtk.Button ();
			this.btnFillDigitalOutputs.CanFocus = true;
			this.btnFillDigitalOutputs.Name = "btnFillDigitalOutputs";
			this.btnFillDigitalOutputs.UseUnderline = true;
			this.btnFillDigitalOutputs.Label = global::Mono.Unix.Catalog.GetString ("Fill Digital Outputs");
			this.vbuttonbox1.Add (this.btnFillDigitalOutputs);
			global::Gtk.ButtonBox.ButtonBoxChild w129 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.btnFillDigitalOutputs]));
			w129.Position = 2;
			w129.Expand = false;
			w129.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnFillSequences = new global::Gtk.Button ();
			this.btnFillSequences.CanFocus = true;
			this.btnFillSequences.Name = "btnFillSequences";
			this.btnFillSequences.UseUnderline = true;
			this.btnFillSequences.Label = global::Mono.Unix.Catalog.GetString ("Fill Sequences");
			this.vbuttonbox1.Add (this.btnFillSequences);
			global::Gtk.ButtonBox.ButtonBoxChild w130 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.btnFillSequences]));
			w130.Position = 3;
			w130.Expand = false;
			w130.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnFillSignals = new global::Gtk.Button ();
			this.btnFillSignals.CanFocus = true;
			this.btnFillSignals.Name = "btnFillSignals";
			this.btnFillSignals.UseUnderline = true;
			this.btnFillSignals.Label = global::Mono.Unix.Catalog.GetString ("Fill Signals");
			this.vbuttonbox1.Add (this.btnFillSignals);
			global::Gtk.ButtonBox.ButtonBoxChild w131 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.btnFillSignals]));
			w131.Position = 4;
			w131.Expand = false;
			w131.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnAlternateBlinkSetup = new global::Gtk.Button ();
			this.btnAlternateBlinkSetup.CanFocus = true;
			this.btnAlternateBlinkSetup.Name = "btnAlternateBlinkSetup";
			this.btnAlternateBlinkSetup.UseUnderline = true;
			this.btnAlternateBlinkSetup.Label = global::Mono.Unix.Catalog.GetString ("Alternate Blink Setup 0Cycle");
			this.vbuttonbox1.Add (this.btnAlternateBlinkSetup);
			global::Gtk.ButtonBox.ButtonBoxChild w132 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.btnAlternateBlinkSetup]));
			w132.Position = 5;
			w132.Expand = false;
			w132.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnAlternateBlinkSetup2 = new global::Gtk.Button ();
			this.btnAlternateBlinkSetup2.CanFocus = true;
			this.btnAlternateBlinkSetup2.Name = "btnAlternateBlinkSetup2";
			this.btnAlternateBlinkSetup2.UseUnderline = true;
			this.btnAlternateBlinkSetup2.Label = global::Mono.Unix.Catalog.GetString ("Alternate Blink Setup 2 0Cycle");
			this.vbuttonbox1.Add (this.btnAlternateBlinkSetup2);
			global::Gtk.ButtonBox.ButtonBoxChild w133 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.btnAlternateBlinkSetup2]));
			w133.Position = 6;
			w133.Expand = false;
			w133.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.button359 = new global::Gtk.Button ();
			this.button359.CanFocus = true;
			this.button359.Name = "button359";
			this.button359.UseUnderline = true;
			this.button359.Label = global::Mono.Unix.Catalog.GetString ("Alternate Blink Setup -1Cycle");
			this.vbuttonbox1.Add (this.button359);
			global::Gtk.ButtonBox.ButtonBoxChild w134 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.button359]));
			w134.Position = 7;
			w134.Expand = false;
			w134.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.button360 = new global::Gtk.Button ();
			this.button360.CanFocus = true;
			this.button360.Name = "button360";
			this.button360.UseUnderline = true;
			this.button360.Label = global::Mono.Unix.Catalog.GetString ("Alternate Blink Setup 2 -1Cycle");
			this.vbuttonbox1.Add (this.button360);
			global::Gtk.ButtonBox.ButtonBoxChild w135 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.button360]));
			w135.Position = 8;
			w135.Expand = false;
			w135.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.button1125 = new global::Gtk.Button ();
			this.button1125.CanFocus = true;
			this.button1125.Name = "button1125";
			this.button1125.UseUnderline = true;
			this.button1125.Label = global::Mono.Unix.Catalog.GetString ("Abstand");
			this.vbuttonbox1.Add (this.button1125);
			global::Gtk.ButtonBox.ButtonBoxChild w136 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.button1125]));
			w136.Position = 9;
			w136.Expand = false;
			w136.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnBoardDifferenceTest = new global::Gtk.Button ();
			this.btnBoardDifferenceTest.CanFocus = true;
			this.btnBoardDifferenceTest.Name = "btnBoardDifferenceTest";
			this.btnBoardDifferenceTest.UseUnderline = true;
			this.btnBoardDifferenceTest.Label = global::Mono.Unix.Catalog.GetString ("SetBoardDifferenceTest");
			this.vbuttonbox1.Add (this.btnBoardDifferenceTest);
			global::Gtk.ButtonBox.ButtonBoxChild w137 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.btnBoardDifferenceTest]));
			w137.Position = 10;
			w137.Expand = false;
			w137.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnRefreshNV = new global::Gtk.Button ();
			this.btnRefreshNV.CanFocus = true;
			this.btnRefreshNV.Name = "btnRefreshNV";
			this.btnRefreshNV.UseUnderline = true;
			this.btnRefreshNV.Label = global::Mono.Unix.Catalog.GetString ("Refresh NodeViews");
			this.vbuttonbox1.Add (this.btnRefreshNV);
			global::Gtk.ButtonBox.ButtonBoxChild w138 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.btnRefreshNV]));
			w138.Position = 11;
			w138.Expand = false;
			w138.Fill = false;
			this.table2.Add (this.vbuttonbox1);
			global::Gtk.Table.TableChild w139 = ((global::Gtk.Table.TableChild)(this.table2 [this.vbuttonbox1]));
			w139.XOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook1.Add (this.table2);
			global::Gtk.Notebook.NotebookChild w140 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.table2]));
			w140.Position = 6;
			// Notebook tab
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("DEBUG");
			this.notebook1.SetTabLabel (this.table2, this.label10);
			this.label10.ShowAll ();
			this.hpanedMain.Add (this.notebook1);
			this.vbox1.Add (this.hpanedMain);
			global::Gtk.Box.BoxChild w142 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hpanedMain]));
			w142.Position = 2;
			// Container child vbox1.Gtk.Box+BoxChild
			this.statusbar1 = new global::Gtk.Statusbar ();
			this.statusbar1.Name = "statusbar1";
			this.statusbar1.Spacing = 6;
			this.statusbar1.HasResizeGrip = false;
			// Container child statusbar1.Gtk.Box+BoxChild
			this.ImageConnectionStatus = new global::Gtk.Image ();
			this.ImageConnectionStatus.WidthRequest = 16;
			this.ImageConnectionStatus.HeightRequest = 16;
			this.ImageConnectionStatus.Name = "ImageConnectionStatus";
			this.ImageConnectionStatus.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-disconnect", global::Gtk.IconSize.Menu);
			this.statusbar1.Add (this.ImageConnectionStatus);
			global::Gtk.Box.BoxChild w143 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.ImageConnectionStatus]));
			w143.Position = 0;
			w143.Expand = false;
			w143.Fill = false;
			// Container child statusbar1.Gtk.Box+BoxChild
			this.lblConnectionStatus = new global::Gtk.Label ();
			this.lblConnectionStatus.Name = "lblConnectionStatus";
			this.lblConnectionStatus.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>NOT</b> connected");
			this.lblConnectionStatus.UseMarkup = true;
			this.statusbar1.Add (this.lblConnectionStatus);
			global::Gtk.Box.BoxChild w144 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.lblConnectionStatus]));
			w144.Position = 1;
			w144.Expand = false;
			w144.Fill = false;
			// Container child statusbar1.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator ();
			this.vseparator1.Name = "vseparator1";
			this.statusbar1.Add (this.vseparator1);
			global::Gtk.Box.BoxChild w145 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.vseparator1]));
			w145.Position = 2;
			w145.Expand = false;
			w145.Fill = false;
			// Container child statusbar1.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Start Time:");
			this.statusbar1.Add (this.label12);
			global::Gtk.Box.BoxChild w146 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.label12]));
			w146.Position = 3;
			w146.Expand = false;
			w146.Fill = false;
			// Container child statusbar1.Gtk.Box+BoxChild
			this.lblStartTime = new global::Gtk.Label ();
			this.lblStartTime.Name = "lblStartTime";
			this.statusbar1.Add (this.lblStartTime);
			global::Gtk.Box.BoxChild w147 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.lblStartTime]));
			w147.Position = 4;
			w147.Expand = false;
			w147.Fill = false;
			// Container child statusbar1.Gtk.Box+BoxChild
			this.vseparator2 = new global::Gtk.VSeparator ();
			this.vseparator2.Name = "vseparator2";
			this.statusbar1.Add (this.vseparator2);
			global::Gtk.Box.BoxChild w148 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.vseparator2]));
			w148.Position = 5;
			w148.Expand = false;
			w148.Fill = false;
			// Container child statusbar1.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Time Elapsed:");
			this.statusbar1.Add (this.label13);
			global::Gtk.Box.BoxChild w149 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.label13]));
			w149.Position = 6;
			w149.Expand = false;
			w149.Fill = false;
			// Container child statusbar1.Gtk.Box+BoxChild
			this.lblTimePassed = new global::Gtk.Label ();
			this.lblTimePassed.Name = "lblTimePassed";
			this.statusbar1.Add (this.lblTimePassed);
			global::Gtk.Box.BoxChild w150 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.lblTimePassed]));
			w150.Position = 7;
			w150.Expand = false;
			w150.Fill = false;
			this.vbox1.Add (this.statusbar1);
			global::Gtk.Box.BoxChild w151 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
			w151.Position = 3;
			w151.Expand = false;
			w151.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 1207;
			this.DefaultHeight = 600;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnKeyPressEvent);
			this.mediaPlayAction.Activated += new global::System.EventHandler (this.OnMediaPlayActionToggled);
			this.mediaStopAction.Activated += new global::System.EventHandler (this.OnMediaStopActionActivated);
			this.saveAsAction.Activated += new global::System.EventHandler (this.OnSaveAsActionActivated);
			this.saveAction.Activated += new global::System.EventHandler (this.OnSaveActionActivated);
			this.openAction.Activated += new global::System.EventHandler (this.OnOpenActionActivated);
			this.refreshAction.Activated += new global::System.EventHandler (this.OnAutoConnectActionActivated);
			this.aboutAction.Activated += new global::System.EventHandler (this.OnAboutActionActivated);
			this.preferencesAction.Activated += new global::System.EventHandler (this.OnPreferencesActionActivated);
			this.cbBoardType.Changed += new global::System.EventHandler (this.OnCbBoardTypeChanged);
			this.cbAREF.Changed += new global::System.EventHandler (this.OnCbAREFChanged);
			this.btnAddAPin.Clicked += new global::System.EventHandler (this.OnBtnAddAPinClicked);
			this.btnCloneAPin.Clicked += new global::System.EventHandler (this.OnBtnCloneAPinClicked);
			this.btnEditAPin.Clicked += new global::System.EventHandler (this.OnBtnEditAPinClicked);
			this.btnRemoveAPin.Clicked += new global::System.EventHandler (this.OnBtnRemoveAPinClicked);
			this.btnClearAPins.Clicked += new global::System.EventHandler (this.OnBtnClearAPinsClicked);
			this.btnAddSignal.Clicked += new global::System.EventHandler (this.OnBtnAddSignalClicked);
			this.btnCloneSignal.Clicked += new global::System.EventHandler (this.OnBtnCloneSignalClicked);
			this.btnEditSignal.Clicked += new global::System.EventHandler (this.OnBtnEditSignalClicked);
			this.btnRemoveSignal.Clicked += new global::System.EventHandler (this.OnBtnRemoveSignalClicked);
			this.btnClearSignals.Clicked += new global::System.EventHandler (this.OnBtnClearSignalsClicked);
			this.btnAddDPin.Clicked += new global::System.EventHandler (this.OnBtnAddDPinClicked);
			this.btnCloneDPin.Clicked += new global::System.EventHandler (this.OnBtnCloneDPinClicked);
			this.btnEditDPin.Clicked += new global::System.EventHandler (this.OnBtnEditDPinClicked);
			this.btnRemoveDPin.Clicked += new global::System.EventHandler (this.OnBtnRemoveDPinClicked);
			this.btnClearDPins.Clicked += new global::System.EventHandler (this.OnBtnClearDPinsClicked);
			this.btnAddSequence.Clicked += new global::System.EventHandler (this.OnBtnAddSequenceClicked);
			this.btnCloneSequence.Clicked += new global::System.EventHandler (this.OnBtnCloneSequenceClicked);
			this.btnEditSequence.Clicked += new global::System.EventHandler (this.OnBtnEditSequenceClicked);
			this.btnRemoveSequence.Clicked += new global::System.EventHandler (this.OnBtnRemoveSequenceClicked);
			this.btnClearSequence.Clicked += new global::System.EventHandler (this.OnBtnClearSequenceClicked);
			this.cbeCSVTimeFormat.Changed += new global::System.EventHandler (this.OnCbeCSVTimeFormatChanged);
			this.cbeCSVSeparator.Changed += new global::System.EventHandler (this.OnCbeCSVSeparatorChanged);
			this.cbCSVUTC.Toggled += new global::System.EventHandler (this.OnCbCSVUTCToggled);
			this.btnCSVFilePathOpen.Clicked += new global::System.EventHandler (this.OnBtnCSVFilePathOpenClicked);
			this.btnCSVOpenFolder.Clicked += new global::System.EventHandler (this.OnBtnCSVOpenFolderClicked);
			this.btnDigitalPingTest.Clicked += new global::System.EventHandler (this.OnBtnDigitalPingTestClicked);
			this.btnFillAnalogInputs.Clicked += new global::System.EventHandler (this.OnBtnFillAnalogInputsClicked);
			this.btnFillDigitalOutputs.Clicked += new global::System.EventHandler (this.OnBtnFillDigitalOutputsClicked);
			this.btnAlternateBlinkSetup.Clicked += new global::System.EventHandler (this.OnBtnAlternateBlinkSetupClicked);
			this.btnAlternateBlinkSetup2.Clicked += new global::System.EventHandler (this.OnBtnAlternateBlinkSetup2Clicked);
			this.button359.Clicked += new global::System.EventHandler (this.OnButton359Clicked);
			this.button360.Clicked += new global::System.EventHandler (this.OnButton360Clicked);
			this.button1125.Clicked += new global::System.EventHandler (this.OnButton1125Clicked);
			this.btnBoardDifferenceTest.Clicked += new global::System.EventHandler (this.OnBtnBoardDifferenceTestClicked);
			this.btnRefreshNV.Clicked += new global::System.EventHandler (this.OnBtnRefreshNVClicked);
		}
	}
}
