
// This file has been generated by the GUI designer. Do not modify.
namespace PrototypeDebugWindow
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.MenuBar menubarMain;
		
		private global::Gtk.Toolbar toolbar1;
		
		private global::Gtk.Notebook notebook1;
		
		private global::Gtk.Table table1;
		
		private global::Gtk.Button btnStopNReset;
		
		private global::Gtk.Frame frame2;
		
		private global::Gtk.Alignment GtkAlignment1;
		
		private global::Gtk.Table table2;
		
		private global::Gtk.Button btnAddDPins;
		
		private global::Gtk.Button btnClearDPins;
		
		private global::Gtk.Button btnRemoveDPin;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		
		private global::Gtk.NodeView nvDigitalPins;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label GtkLabel16;
		
		private global::Gtk.Frame frame3;
		
		private global::Gtk.Alignment GtkAlignment4;
		
		private global::Gtk.Table table3;
		
		private global::Gtk.Button btnAddAPin;
		
		private global::Gtk.Button btnClearDPins1;
		
		private global::Gtk.Button btnRemoveDPin1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow3;
		
		private global::Gtk.NodeView nvAnalogPins;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Label GtkLabel21;
		
		private global::Gtk.VButtonBox vbuttonbox1;
		
		private global::Gtk.Button btnDigitalPingTest;
		
		private global::Gtk.Button btnBlinkSequenceTest;
		
		private global::Gtk.Button btnDoubleBlink;
		
		private global::Gtk.Button button70;
		
		private global::Gtk.Button button71;
		
		private global::Gtk.Button button72;
		
		private global::Gtk.Button button73;
		
		private global::Gtk.Button button74;
		
		private global::Gtk.Button button75;
		
		private global::Gtk.Button button76;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView tvLog;
		
		private global::Gtk.Statusbar statusbar1;
		
		private global::Gtk.Image ImageConnectionStatus;
		
		private global::Gtk.Label lblConnectionStatus;
		
		private global::Gtk.VSeparator vseparator1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PrototypeDebugWindow.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.WidthRequest = 800;
			this.HeightRequest = 600;
			this.Name = "PrototypeDebugWindow.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			// Container child PrototypeDebugWindow.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubarMain'/></ui>");
			this.menubarMain = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubarMain")));
			this.menubarMain.Name = "menubarMain";
			this.vbox1.Add (this.menubarMain);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubarMain]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar1'/></ui>");
			this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
			this.toolbar1.Name = "toolbar1";
			this.toolbar1.ShowArrow = false;
			this.vbox1.Add (this.toolbar1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.toolbar1]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.btnStopNReset = new global::Gtk.Button ();
			this.btnStopNReset.HeightRequest = 26;
			this.btnStopNReset.CanFocus = true;
			this.btnStopNReset.Name = "btnStopNReset";
			this.btnStopNReset.UseUnderline = true;
			this.btnStopNReset.Label = global::Mono.Unix.Catalog.GetString ("Stop and Reset\n");
			this.table1.Add (this.btnStopNReset);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnStopNReset]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.RightAttach = ((uint)(3));
			w4.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table1.Gtk.Table+TableChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.table2 = new global::Gtk.Table (((uint)(4)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.btnAddDPins = new global::Gtk.Button ();
			this.btnAddDPins.HeightRequest = 26;
			this.btnAddDPins.CanFocus = true;
			this.btnAddDPins.Name = "btnAddDPins";
			this.btnAddDPins.UseUnderline = true;
			this.btnAddDPins.Label = global::Mono.Unix.Catalog.GetString ("Add digital Output...");
			global::Gtk.Image w5 = new global::Gtk.Image ();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			this.btnAddDPins.Image = w5;
			this.table2.Add (this.btnAddDPins);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2 [this.btnAddDPins]));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table2.Gtk.Table+TableChild
			this.btnClearDPins = new global::Gtk.Button ();
			this.btnClearDPins.HeightRequest = 26;
			this.btnClearDPins.CanFocus = true;
			this.btnClearDPins.Name = "btnClearDPins";
			this.btnClearDPins.UseUnderline = true;
			this.btnClearDPins.Label = global::Mono.Unix.Catalog.GetString ("Clear");
			global::Gtk.Image w7 = new global::Gtk.Image ();
			w7.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-clear", global::Gtk.IconSize.Menu);
			this.btnClearDPins.Image = w7;
			this.table2.Add (this.btnClearDPins);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table2 [this.btnClearDPins]));
			w8.TopAttach = ((uint)(2));
			w8.BottomAttach = ((uint)(3));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table2.Gtk.Table+TableChild
			this.btnRemoveDPin = new global::Gtk.Button ();
			this.btnRemoveDPin.HeightRequest = 26;
			this.btnRemoveDPin.CanFocus = true;
			this.btnRemoveDPin.Name = "btnRemoveDPin";
			this.btnRemoveDPin.UseUnderline = true;
			this.btnRemoveDPin.Label = global::Mono.Unix.Catalog.GetString ("Remove digital Output");
			global::Gtk.Image w9 = new global::Gtk.Image ();
			w9.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-remove", global::Gtk.IconSize.Menu);
			this.btnRemoveDPin.Image = w9;
			this.table2.Add (this.btnRemoveDPin);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table2 [this.btnRemoveDPin]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table2.Gtk.Table+TableChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.nvDigitalPins = new global::Gtk.NodeView ();
			this.nvDigitalPins.CanFocus = true;
			this.nvDigitalPins.Name = "nvDigitalPins";
			this.GtkScrolledWindow2.Add (this.nvDigitalPins);
			this.table2.Add (this.GtkScrolledWindow2);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2 [this.GtkScrolledWindow2]));
			w12.BottomAttach = ((uint)(4));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			// Container child table2.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.table2.Add (this.label2);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table2 [this.label2]));
			w13.TopAttach = ((uint)(3));
			w13.BottomAttach = ((uint)(4));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment1.Add (this.table2);
			this.frame2.Add (this.GtkAlignment1);
			this.GtkLabel16 = new global::Gtk.Label ();
			this.GtkLabel16.Name = "GtkLabel16";
			this.GtkLabel16.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Digital Outputs</b>");
			this.GtkLabel16.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel16;
			this.table1.Add (this.frame2);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1 [this.frame2]));
			w16.TopAttach = ((uint)(1));
			w16.BottomAttach = ((uint)(2));
			w16.LeftAttach = ((uint)(2));
			w16.RightAttach = ((uint)(3));
			// Container child table1.Gtk.Table+TableChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.table3 = new global::Gtk.Table (((uint)(4)), ((uint)(2)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.btnAddAPin = new global::Gtk.Button ();
			this.btnAddAPin.HeightRequest = 26;
			this.btnAddAPin.CanFocus = true;
			this.btnAddAPin.Name = "btnAddAPin";
			this.btnAddAPin.UseUnderline = true;
			this.btnAddAPin.Label = global::Mono.Unix.Catalog.GetString ("Add analog Input...");
			global::Gtk.Image w17 = new global::Gtk.Image ();
			w17.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			this.btnAddAPin.Image = w17;
			this.table3.Add (this.btnAddAPin);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table3 [this.btnAddAPin]));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table3.Gtk.Table+TableChild
			this.btnClearDPins1 = new global::Gtk.Button ();
			this.btnClearDPins1.HeightRequest = 26;
			this.btnClearDPins1.CanFocus = true;
			this.btnClearDPins1.Name = "btnClearDPins1";
			this.btnClearDPins1.UseUnderline = true;
			this.btnClearDPins1.Label = global::Mono.Unix.Catalog.GetString ("Clear");
			global::Gtk.Image w19 = new global::Gtk.Image ();
			w19.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-clear", global::Gtk.IconSize.Menu);
			this.btnClearDPins1.Image = w19;
			this.table3.Add (this.btnClearDPins1);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table3 [this.btnClearDPins1]));
			w20.TopAttach = ((uint)(2));
			w20.BottomAttach = ((uint)(3));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table3.Gtk.Table+TableChild
			this.btnRemoveDPin1 = new global::Gtk.Button ();
			this.btnRemoveDPin1.HeightRequest = 26;
			this.btnRemoveDPin1.CanFocus = true;
			this.btnRemoveDPin1.Name = "btnRemoveDPin1";
			this.btnRemoveDPin1.UseUnderline = true;
			this.btnRemoveDPin1.Label = global::Mono.Unix.Catalog.GetString ("Remove analog Input");
			global::Gtk.Image w21 = new global::Gtk.Image ();
			w21.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-remove", global::Gtk.IconSize.Menu);
			this.btnRemoveDPin1.Image = w21;
			this.table3.Add (this.btnRemoveDPin1);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table3 [this.btnRemoveDPin1]));
			w22.TopAttach = ((uint)(1));
			w22.BottomAttach = ((uint)(2));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table3.Gtk.Table+TableChild
			this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
			this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
			this.nvAnalogPins = new global::Gtk.NodeView ();
			this.nvAnalogPins.CanFocus = true;
			this.nvAnalogPins.Name = "nvAnalogPins";
			this.nvAnalogPins.Reorderable = true;
			this.nvAnalogPins.HoverExpand = true;
			this.GtkScrolledWindow3.Add (this.nvAnalogPins);
			this.table3.Add (this.GtkScrolledWindow3);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table3 [this.GtkScrolledWindow3]));
			w24.BottomAttach = ((uint)(4));
			w24.LeftAttach = ((uint)(1));
			w24.RightAttach = ((uint)(2));
			// Container child table3.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.table3.Add (this.label3);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table3 [this.label3]));
			w25.TopAttach = ((uint)(3));
			w25.BottomAttach = ((uint)(4));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment4.Add (this.table3);
			this.frame3.Add (this.GtkAlignment4);
			this.GtkLabel21 = new global::Gtk.Label ();
			this.GtkLabel21.Name = "GtkLabel21";
			this.GtkLabel21.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Analog Inputs</b>");
			this.GtkLabel21.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel21;
			this.table1.Add (this.frame3);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table1 [this.frame3]));
			w28.LeftAttach = ((uint)(2));
			w28.RightAttach = ((uint)(3));
			// Container child table1.Gtk.Table+TableChild
			this.vbuttonbox1 = new global::Gtk.VButtonBox ();
			this.vbuttonbox1.Name = "vbuttonbox1";
			this.vbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnDigitalPingTest = new global::Gtk.Button ();
			this.btnDigitalPingTest.CanFocus = true;
			this.btnDigitalPingTest.Name = "btnDigitalPingTest";
			this.btnDigitalPingTest.UseUnderline = true;
			this.btnDigitalPingTest.Label = global::Mono.Unix.Catalog.GetString ("DigitalPingTest");
			this.vbuttonbox1.Add (this.btnDigitalPingTest);
			global::Gtk.ButtonBox.ButtonBoxChild w29 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.btnDigitalPingTest]));
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnBlinkSequenceTest = new global::Gtk.Button ();
			this.btnBlinkSequenceTest.CanFocus = true;
			this.btnBlinkSequenceTest.Name = "btnBlinkSequenceTest";
			this.btnBlinkSequenceTest.UseUnderline = true;
			this.btnBlinkSequenceTest.Label = global::Mono.Unix.Catalog.GetString ("BlinkSequenceTest");
			this.vbuttonbox1.Add (this.btnBlinkSequenceTest);
			global::Gtk.ButtonBox.ButtonBoxChild w30 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.btnBlinkSequenceTest]));
			w30.Position = 1;
			w30.Expand = false;
			w30.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnDoubleBlink = new global::Gtk.Button ();
			this.btnDoubleBlink.CanFocus = true;
			this.btnDoubleBlink.Name = "btnDoubleBlink";
			this.btnDoubleBlink.UseUnderline = true;
			this.btnDoubleBlink.Label = global::Mono.Unix.Catalog.GetString ("UberKewlPhaseShiftDoubleBlink");
			this.vbuttonbox1.Add (this.btnDoubleBlink);
			global::Gtk.ButtonBox.ButtonBoxChild w31 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.btnDoubleBlink]));
			w31.Position = 2;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.button70 = new global::Gtk.Button ();
			this.button70.CanFocus = true;
			this.button70.Name = "button70";
			this.button70.UseUnderline = true;
			this.button70.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.vbuttonbox1.Add (this.button70);
			global::Gtk.ButtonBox.ButtonBoxChild w32 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.button70]));
			w32.Position = 3;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.button71 = new global::Gtk.Button ();
			this.button71.CanFocus = true;
			this.button71.Name = "button71";
			this.button71.UseUnderline = true;
			this.button71.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.vbuttonbox1.Add (this.button71);
			global::Gtk.ButtonBox.ButtonBoxChild w33 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.button71]));
			w33.Position = 4;
			w33.Expand = false;
			w33.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.button72 = new global::Gtk.Button ();
			this.button72.CanFocus = true;
			this.button72.Name = "button72";
			this.button72.UseUnderline = true;
			this.button72.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.vbuttonbox1.Add (this.button72);
			global::Gtk.ButtonBox.ButtonBoxChild w34 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.button72]));
			w34.Position = 5;
			w34.Expand = false;
			w34.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.button73 = new global::Gtk.Button ();
			this.button73.CanFocus = true;
			this.button73.Name = "button73";
			this.button73.UseUnderline = true;
			this.button73.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.vbuttonbox1.Add (this.button73);
			global::Gtk.ButtonBox.ButtonBoxChild w35 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.button73]));
			w35.Position = 6;
			w35.Expand = false;
			w35.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.button74 = new global::Gtk.Button ();
			this.button74.CanFocus = true;
			this.button74.Name = "button74";
			this.button74.UseUnderline = true;
			this.button74.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.vbuttonbox1.Add (this.button74);
			global::Gtk.ButtonBox.ButtonBoxChild w36 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.button74]));
			w36.Position = 7;
			w36.Expand = false;
			w36.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.button75 = new global::Gtk.Button ();
			this.button75.CanFocus = true;
			this.button75.Name = "button75";
			this.button75.UseUnderline = true;
			this.button75.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.vbuttonbox1.Add (this.button75);
			global::Gtk.ButtonBox.ButtonBoxChild w37 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.button75]));
			w37.Position = 8;
			w37.Expand = false;
			w37.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.button76 = new global::Gtk.Button ();
			this.button76.CanFocus = true;
			this.button76.Name = "button76";
			this.button76.UseUnderline = true;
			this.button76.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.vbuttonbox1.Add (this.button76);
			global::Gtk.ButtonBox.ButtonBoxChild w38 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.button76]));
			w38.Position = 9;
			w38.Expand = false;
			w38.Fill = false;
			this.table1.Add (this.vbuttonbox1);
			global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.table1 [this.vbuttonbox1]));
			w39.BottomAttach = ((uint)(2));
			w39.XOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook1.Add (this.table1);
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("page1");
			this.notebook1.SetTabLabel (this.table1, this.label1);
			this.label1.ShowAll ();
			this.vbox1.Add (this.notebook1);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook1]));
			w41.Position = 2;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvLog = new global::Gtk.TextView ();
			this.tvLog.WidthRequest = 150;
			this.tvLog.CanFocus = true;
			this.tvLog.Name = "tvLog";
			this.GtkScrolledWindow.Add (this.tvLog);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w43.Position = 3;
			// Container child vbox1.Gtk.Box+BoxChild
			this.statusbar1 = new global::Gtk.Statusbar ();
			this.statusbar1.Name = "statusbar1";
			this.statusbar1.Spacing = 6;
			this.statusbar1.HasResizeGrip = false;
			// Container child statusbar1.Gtk.Box+BoxChild
			this.ImageConnectionStatus = new global::Gtk.Image ();
			this.ImageConnectionStatus.WidthRequest = 16;
			this.ImageConnectionStatus.HeightRequest = 16;
			this.ImageConnectionStatus.Name = "ImageConnectionStatus";
			this.ImageConnectionStatus.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-disconnect", global::Gtk.IconSize.Menu);
			this.statusbar1.Add (this.ImageConnectionStatus);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.ImageConnectionStatus]));
			w44.Position = 0;
			w44.Expand = false;
			w44.Fill = false;
			// Container child statusbar1.Gtk.Box+BoxChild
			this.lblConnectionStatus = new global::Gtk.Label ();
			this.lblConnectionStatus.Name = "lblConnectionStatus";
			this.lblConnectionStatus.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>NOT</b> connected");
			this.lblConnectionStatus.UseMarkup = true;
			this.statusbar1.Add (this.lblConnectionStatus);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.lblConnectionStatus]));
			w45.Position = 1;
			w45.Expand = false;
			w45.Fill = false;
			// Container child statusbar1.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator ();
			this.vseparator1.Name = "vseparator1";
			this.statusbar1.Add (this.vseparator1);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.vseparator1]));
			w46.Position = 2;
			w46.Expand = false;
			w46.Fill = false;
			this.vbox1.Add (this.statusbar1);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
			w47.Position = 4;
			w47.Expand = false;
			w47.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 800;
			this.DefaultHeight = 600;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnKeyPressEvent);
			this.btnRemoveDPin1.Clicked += new global::System.EventHandler (this.OnBtnRemoveDPin1Clicked);
			this.btnClearDPins1.Clicked += new global::System.EventHandler (this.OnBtnClearDPins1Clicked);
			this.btnAddAPin.Clicked += new global::System.EventHandler (this.OnBtnAddAPinClicked);
			this.btnRemoveDPin.Clicked += new global::System.EventHandler (this.OnBtnRemoveDPinClicked);
			this.btnClearDPins.Clicked += new global::System.EventHandler (this.OnBtnClearDPinsClicked);
			this.btnAddDPins.Clicked += new global::System.EventHandler (this.OnBtnAddDPinClicked);
		}
	}
}
