
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::MCUWidget.MCUWidget mcuwidget1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.mcuwidget1 = new global::MCUWidget.MCUWidget ();
		this.mcuwidget1.Events = ((global::Gdk.EventMask)(256));
		this.mcuwidget1.Name = "mcuwidget1";
		this.Add (this.mcuwidget1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 286;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
