
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Table tableMain;
	
	private global::Gtk.Button btnGO;
	
	private global::Gtk.Frame framePlot;
	
	private global::Gtk.Alignment GtkAlignment;
	
	private global::Gtk.Label GtkLabel1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.tableMain = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
		this.tableMain.Name = "tableMain";
		this.tableMain.RowSpacing = ((uint)(6));
		this.tableMain.ColumnSpacing = ((uint)(6));
		// Container child tableMain.Gtk.Table+TableChild
		this.btnGO = new global::Gtk.Button ();
		this.btnGO.CanFocus = true;
		this.btnGO.Name = "btnGO";
		this.btnGO.UseUnderline = true;
		this.btnGO.Label = global::Mono.Unix.Catalog.GetString ("GO");
		this.tableMain.Add (this.btnGO);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.tableMain [this.btnGO]));
		w1.TopAttach = ((uint)(2));
		w1.BottomAttach = ((uint)(3));
		w1.RightAttach = ((uint)(2));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableMain.Gtk.Table+TableChild
		this.framePlot = new global::Gtk.Frame ();
		this.framePlot.Name = "framePlot";
		this.framePlot.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child framePlot.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		this.framePlot.Add (this.GtkAlignment);
		this.GtkLabel1 = new global::Gtk.Label ();
		this.GtkLabel1.Name = "GtkLabel1";
		this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Plot</b>");
		this.GtkLabel1.UseMarkup = true;
		this.framePlot.LabelWidget = this.GtkLabel1;
		this.tableMain.Add (this.framePlot);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.tableMain [this.framePlot]));
		w3.BottomAttach = ((uint)(2));
		w3.RightAttach = ((uint)(2));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		this.Add (this.tableMain);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 299;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnGO.Clicked += new global::System.EventHandler (this.OnBtnGOClicked);
	}
}
