
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.HBox HBoxConnection;
	
	private global::Gtk.Label LabelSerialPort;
	
	private global::Gtk.ComboBox CBSerialPorts;
	
	private global::Gtk.Button BtnConnect;
	
	private global::Gtk.Button BtnConnectRefresh;
	
	private global::Gtk.Button bntAutoConnect;
	
	private global::Gtk.Notebook nbMain;
	
	private global::Gtk.HBox HBoxControll;
	
	private global::Gtk.VBox VBoxDigitalPinNames;
	
	private global::Gtk.Label LabelPin13;
	
	private global::Gtk.Label LabelPin12;
	
	private global::Gtk.Label LabelPin11;
	
	private global::Gtk.Label LabelPin10;
	
	private global::Gtk.Label LabelPin9;
	
	private global::Gtk.Label LabelPin8;
	
	private global::Gtk.Label LabelPin14;
	
	private global::Gtk.Label LabelPin15;
	
	private global::Gtk.Label LabelPin16;
	
	private global::Gtk.Label LabelPin21;
	
	private global::Gtk.Label LabelPin20;
	
	private global::Gtk.Label LabelPin19;
	
	private global::Gtk.Label LabelPin18;
	
	private global::Gtk.Label LabelPin17;
	
	private global::Gtk.VBox VBoxDigitalPinModes;
	
	private global::Gtk.ComboBox cbDPin13;
	
	private global::Gtk.ComboBox cbDPin12;
	
	private global::Gtk.ComboBox cbDPin11;
	
	private global::Gtk.ComboBox cbDPin10;
	
	private global::Gtk.ComboBox cbDPin9;
	
	private global::Gtk.ComboBox cbDPin8;
	
	private global::Gtk.ComboBox cbDPin7;
	
	private global::Gtk.ComboBox cbDPin6;
	
	private global::Gtk.ComboBox cbDPin5;
	
	private global::Gtk.ComboBox cbDPin4;
	
	private global::Gtk.ComboBox cbDPin3;
	
	private global::Gtk.ComboBox cbDPin2;
	
	private global::Gtk.ComboBox cbDPin1;
	
	private global::Gtk.ComboBox cbDPin;
	
	private global::Gtk.VBox VBoxDigitalPinStates;
	
	private global::Gtk.CheckButton cbtnDPin13;
	
	private global::Gtk.CheckButton cbtnDPin12;
	
	private global::Gtk.CheckButton cbtnDPin11;
	
	private global::Gtk.CheckButton cbtnDPin10;
	
	private global::Gtk.CheckButton cbtnDPin9;
	
	private global::Gtk.CheckButton cbtnDPin8;
	
	private global::Gtk.CheckButton cbtnDPin;
	
	private global::Gtk.CheckButton cbtnDPin1;
	
	private global::Gtk.CheckButton cbtnDPin2;
	
	private global::Gtk.CheckButton cbtnDPin3;
	
	private global::Gtk.CheckButton cbtnDPin4;
	
	private global::Gtk.CheckButton cbtnDPin5;
	
	private global::Gtk.CheckButton cbtnDPin6;
	
	private global::Gtk.CheckButton cbtnDPin7;
	
	private global::Gtk.VSeparator vseparator1;
	
	private global::Gtk.VBox VBoxAnalogPinNames;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.Label LabelA5;
	
	private global::Gtk.Label LabelA4;
	
	private global::Gtk.Label LabelA3;
	
	private global::Gtk.Label LabelA;
	
	private global::Gtk.Label LabelA1;
	
	private global::Gtk.Label LabelA2;
	
	private global::Gtk.VBox VBoxAnalogPinModes;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.ComboBox CBAnalogPin5Mode;
	
	private global::Gtk.ComboBox combobox16;
	
	private global::Gtk.ComboBox combobox17;
	
	private global::Gtk.ComboBox combobox18;
	
	private global::Gtk.ComboBox combobox20;
	
	private global::Gtk.ComboBox CBAnalogPin0Mode;
	
	private global::Gtk.VBox VBoxAnalogValues;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.Label LabelValueA5;
	
	private global::Gtk.Label LabelValueA4;
	
	private global::Gtk.Label LabelValueA3;
	
	private global::Gtk.Label LabelValueA;
	
	private global::Gtk.Label LabelValueA1;
	
	private global::Gtk.Label LabelValueA2;
	
	private global::Gtk.VBox VBoxAnalogPinOutput;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.HScale HScaleAnalogPinFive;
	
	private global::Gtk.HScale hscale2;
	
	private global::Gtk.HScale hscale3;
	
	private global::Gtk.HScale hscale4;
	
	private global::Gtk.HScale hscale5;
	
	private global::Gtk.HScale HScaleAnalogPinNull;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.Table table1;
	
	private global::Gtk.Table tableValues;
	
	private global::Gtk.Button btnDataRefreshAll;
	
	private global::Gtk.Button button1;
	
	private global::Gtk.Button button2;
	
	private global::Gtk.Button button4;
	
	private global::Gtk.Button button5;
	
	private global::Gtk.Button button6;
	
	private global::Gtk.Button button7;
	
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.Label label18;
	
	private global::Gtk.Label label19;
	
	private global::Gtk.Label label20;
	
	private global::Gtk.Label label21;
	
	private global::Gtk.Label label7;
	
	private global::Gtk.Label label8;
	
	private global::Gtk.Label labelModeBitMask;
	
	private global::Gtk.Label labelModel;
	
	private global::Gtk.Label labelNrAnaPin;
	
	private global::Gtk.Label labelNrDigiPin;
	
	private global::Gtk.Label labelOutputBitMask;
	
	private global::Gtk.Label labelVersion;
	
	private global::Gtk.Label label6;
	
	private global::Gtk.Statusbar statusbar1;
	
	private global::Gtk.Label LabelStatus;
	
	private global::Gtk.Label LabelConnectionStatus;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("CmdMessengerTestsController");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-preferences", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.HBoxConnection = new global::Gtk.HBox ();
		this.HBoxConnection.Name = "HBoxConnection";
		this.HBoxConnection.Spacing = 6;
		// Container child HBoxConnection.Gtk.Box+BoxChild
		this.LabelSerialPort = new global::Gtk.Label ();
		this.LabelSerialPort.Name = "LabelSerialPort";
		this.LabelSerialPort.Xalign = 1F;
		this.LabelSerialPort.LabelProp = global::Mono.Unix.Catalog.GetString ("SerialPort:");
		this.LabelSerialPort.Justify = ((global::Gtk.Justification)(1));
		this.HBoxConnection.Add (this.LabelSerialPort);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.HBoxConnection [this.LabelSerialPort]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child HBoxConnection.Gtk.Box+BoxChild
		this.CBSerialPorts = global::Gtk.ComboBox.NewText ();
		this.CBSerialPorts.Name = "CBSerialPorts";
		this.HBoxConnection.Add (this.CBSerialPorts);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.HBoxConnection [this.CBSerialPorts]));
		w2.Position = 1;
		// Container child HBoxConnection.Gtk.Box+BoxChild
		this.BtnConnect = new global::Gtk.Button ();
		this.BtnConnect.WidthRequest = 150;
		this.BtnConnect.CanFocus = true;
		this.BtnConnect.Name = "BtnConnect";
		this.BtnConnect.UseUnderline = true;
		this.BtnConnect.Label = global::Mono.Unix.Catalog.GetString ("Connect");
		this.HBoxConnection.Add (this.BtnConnect);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.HBoxConnection [this.BtnConnect]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child HBoxConnection.Gtk.Box+BoxChild
		this.BtnConnectRefresh = new global::Gtk.Button ();
		this.BtnConnectRefresh.WidthRequest = 150;
		this.BtnConnectRefresh.CanFocus = true;
		this.BtnConnectRefresh.Name = "BtnConnectRefresh";
		this.BtnConnectRefresh.UseUnderline = true;
		this.BtnConnectRefresh.Label = global::Mono.Unix.Catalog.GetString ("Refresh");
		this.HBoxConnection.Add (this.BtnConnectRefresh);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.HBoxConnection [this.BtnConnectRefresh]));
		w4.PackType = ((global::Gtk.PackType)(1));
		w4.Position = 3;
		w4.Expand = false;
		w4.Fill = false;
		// Container child HBoxConnection.Gtk.Box+BoxChild
		this.bntAutoConnect = new global::Gtk.Button ();
		this.bntAutoConnect.WidthRequest = 150;
		this.bntAutoConnect.CanFocus = true;
		this.bntAutoConnect.Name = "bntAutoConnect";
		this.bntAutoConnect.UseUnderline = true;
		this.bntAutoConnect.Label = global::Mono.Unix.Catalog.GetString ("Auto Connect");
		this.HBoxConnection.Add (this.bntAutoConnect);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.HBoxConnection [this.bntAutoConnect]));
		w5.PackType = ((global::Gtk.PackType)(1));
		w5.Position = 4;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox3.Add (this.HBoxConnection);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.HBoxConnection]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.nbMain = new global::Gtk.Notebook ();
		this.nbMain.CanFocus = true;
		this.nbMain.Name = "nbMain";
		this.nbMain.CurrentPage = 1;
		// Container child nbMain.Gtk.Notebook+NotebookChild
		this.HBoxControll = new global::Gtk.HBox ();
		this.HBoxControll.Name = "HBoxControll";
		this.HBoxControll.Spacing = 6;
		this.HBoxControll.BorderWidth = ((uint)(3));
		// Container child HBoxControll.Gtk.Box+BoxChild
		this.VBoxDigitalPinNames = new global::Gtk.VBox ();
		this.VBoxDigitalPinNames.Name = "VBoxDigitalPinNames";
		this.VBoxDigitalPinNames.Homogeneous = true;
		this.VBoxDigitalPinNames.Spacing = 6;
		// Container child VBoxDigitalPinNames.Gtk.Box+BoxChild
		this.LabelPin13 = new global::Gtk.Label ();
		this.LabelPin13.Name = "LabelPin13";
		this.LabelPin13.LabelProp = global::Mono.Unix.Catalog.GetString ("Pin13");
		this.VBoxDigitalPinNames.Add (this.LabelPin13);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinNames [this.LabelPin13]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child VBoxDigitalPinNames.Gtk.Box+BoxChild
		this.LabelPin12 = new global::Gtk.Label ();
		this.LabelPin12.Name = "LabelPin12";
		this.LabelPin12.LabelProp = global::Mono.Unix.Catalog.GetString ("Pin12");
		this.VBoxDigitalPinNames.Add (this.LabelPin12);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinNames [this.LabelPin12]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child VBoxDigitalPinNames.Gtk.Box+BoxChild
		this.LabelPin11 = new global::Gtk.Label ();
		this.LabelPin11.Name = "LabelPin11";
		this.LabelPin11.LabelProp = global::Mono.Unix.Catalog.GetString ("Pin11");
		this.VBoxDigitalPinNames.Add (this.LabelPin11);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinNames [this.LabelPin11]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		// Container child VBoxDigitalPinNames.Gtk.Box+BoxChild
		this.LabelPin10 = new global::Gtk.Label ();
		this.LabelPin10.Name = "LabelPin10";
		this.LabelPin10.LabelProp = global::Mono.Unix.Catalog.GetString ("Pin10");
		this.VBoxDigitalPinNames.Add (this.LabelPin10);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinNames [this.LabelPin10]));
		w10.Position = 3;
		w10.Expand = false;
		w10.Fill = false;
		// Container child VBoxDigitalPinNames.Gtk.Box+BoxChild
		this.LabelPin9 = new global::Gtk.Label ();
		this.LabelPin9.Name = "LabelPin9";
		this.LabelPin9.LabelProp = global::Mono.Unix.Catalog.GetString ("Pin9");
		this.VBoxDigitalPinNames.Add (this.LabelPin9);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinNames [this.LabelPin9]));
		w11.Position = 4;
		w11.Expand = false;
		w11.Fill = false;
		// Container child VBoxDigitalPinNames.Gtk.Box+BoxChild
		this.LabelPin8 = new global::Gtk.Label ();
		this.LabelPin8.Name = "LabelPin8";
		this.LabelPin8.LabelProp = global::Mono.Unix.Catalog.GetString ("Pin8");
		this.VBoxDigitalPinNames.Add (this.LabelPin8);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinNames [this.LabelPin8]));
		w12.Position = 5;
		w12.Expand = false;
		w12.Fill = false;
		// Container child VBoxDigitalPinNames.Gtk.Box+BoxChild
		this.LabelPin14 = new global::Gtk.Label ();
		this.LabelPin14.Name = "LabelPin14";
		this.LabelPin14.LabelProp = global::Mono.Unix.Catalog.GetString ("Pin7");
		this.VBoxDigitalPinNames.Add (this.LabelPin14);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinNames [this.LabelPin14]));
		w13.Position = 6;
		w13.Expand = false;
		w13.Fill = false;
		// Container child VBoxDigitalPinNames.Gtk.Box+BoxChild
		this.LabelPin15 = new global::Gtk.Label ();
		this.LabelPin15.Name = "LabelPin15";
		this.LabelPin15.LabelProp = global::Mono.Unix.Catalog.GetString ("Pin6");
		this.VBoxDigitalPinNames.Add (this.LabelPin15);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinNames [this.LabelPin15]));
		w14.Position = 7;
		w14.Expand = false;
		w14.Fill = false;
		// Container child VBoxDigitalPinNames.Gtk.Box+BoxChild
		this.LabelPin16 = new global::Gtk.Label ();
		this.LabelPin16.Name = "LabelPin16";
		this.LabelPin16.LabelProp = global::Mono.Unix.Catalog.GetString ("Pin5");
		this.VBoxDigitalPinNames.Add (this.LabelPin16);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinNames [this.LabelPin16]));
		w15.Position = 8;
		w15.Expand = false;
		w15.Fill = false;
		// Container child VBoxDigitalPinNames.Gtk.Box+BoxChild
		this.LabelPin21 = new global::Gtk.Label ();
		this.LabelPin21.Name = "LabelPin21";
		this.LabelPin21.LabelProp = global::Mono.Unix.Catalog.GetString ("Pin0");
		this.VBoxDigitalPinNames.Add (this.LabelPin21);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinNames [this.LabelPin21]));
		w16.PackType = ((global::Gtk.PackType)(1));
		w16.Position = 9;
		w16.Expand = false;
		w16.Fill = false;
		// Container child VBoxDigitalPinNames.Gtk.Box+BoxChild
		this.LabelPin20 = new global::Gtk.Label ();
		this.LabelPin20.Name = "LabelPin20";
		this.LabelPin20.LabelProp = global::Mono.Unix.Catalog.GetString ("Pin1");
		this.VBoxDigitalPinNames.Add (this.LabelPin20);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinNames [this.LabelPin20]));
		w17.PackType = ((global::Gtk.PackType)(1));
		w17.Position = 10;
		w17.Expand = false;
		w17.Fill = false;
		// Container child VBoxDigitalPinNames.Gtk.Box+BoxChild
		this.LabelPin19 = new global::Gtk.Label ();
		this.LabelPin19.Name = "LabelPin19";
		this.LabelPin19.LabelProp = global::Mono.Unix.Catalog.GetString ("Pin2");
		this.VBoxDigitalPinNames.Add (this.LabelPin19);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinNames [this.LabelPin19]));
		w18.PackType = ((global::Gtk.PackType)(1));
		w18.Position = 11;
		w18.Expand = false;
		w18.Fill = false;
		// Container child VBoxDigitalPinNames.Gtk.Box+BoxChild
		this.LabelPin18 = new global::Gtk.Label ();
		this.LabelPin18.Name = "LabelPin18";
		this.LabelPin18.LabelProp = global::Mono.Unix.Catalog.GetString ("Pin3");
		this.VBoxDigitalPinNames.Add (this.LabelPin18);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinNames [this.LabelPin18]));
		w19.PackType = ((global::Gtk.PackType)(1));
		w19.Position = 12;
		w19.Expand = false;
		w19.Fill = false;
		// Container child VBoxDigitalPinNames.Gtk.Box+BoxChild
		this.LabelPin17 = new global::Gtk.Label ();
		this.LabelPin17.Name = "LabelPin17";
		this.LabelPin17.LabelProp = global::Mono.Unix.Catalog.GetString ("Pin4");
		this.VBoxDigitalPinNames.Add (this.LabelPin17);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinNames [this.LabelPin17]));
		w20.PackType = ((global::Gtk.PackType)(1));
		w20.Position = 13;
		w20.Expand = false;
		w20.Fill = false;
		this.HBoxControll.Add (this.VBoxDigitalPinNames);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.HBoxControll [this.VBoxDigitalPinNames]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		w21.Padding = ((uint)(3));
		// Container child HBoxControll.Gtk.Box+BoxChild
		this.VBoxDigitalPinModes = new global::Gtk.VBox ();
		this.VBoxDigitalPinModes.Name = "VBoxDigitalPinModes";
		this.VBoxDigitalPinModes.Homogeneous = true;
		this.VBoxDigitalPinModes.Spacing = 6;
		// Container child VBoxDigitalPinModes.Gtk.Box+BoxChild
		this.cbDPin13 = global::Gtk.ComboBox.NewText ();
		this.cbDPin13.AppendText (global::Mono.Unix.Catalog.GetString ("INPUT"));
		this.cbDPin13.AppendText (global::Mono.Unix.Catalog.GetString ("OUTPUT"));
		this.cbDPin13.Name = "cbDPin13";
		this.cbDPin13.Active = 1;
		this.VBoxDigitalPinModes.Add (this.cbDPin13);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinModes [this.cbDPin13]));
		w22.Position = 0;
		w22.Expand = false;
		w22.Fill = false;
		// Container child VBoxDigitalPinModes.Gtk.Box+BoxChild
		this.cbDPin12 = global::Gtk.ComboBox.NewText ();
		this.cbDPin12.AppendText (global::Mono.Unix.Catalog.GetString ("INPUT"));
		this.cbDPin12.AppendText (global::Mono.Unix.Catalog.GetString ("OUTPUT"));
		this.cbDPin12.Name = "cbDPin12";
		this.cbDPin12.Active = 1;
		this.VBoxDigitalPinModes.Add (this.cbDPin12);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinModes [this.cbDPin12]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		// Container child VBoxDigitalPinModes.Gtk.Box+BoxChild
		this.cbDPin11 = global::Gtk.ComboBox.NewText ();
		this.cbDPin11.AppendText (global::Mono.Unix.Catalog.GetString ("INPUT"));
		this.cbDPin11.AppendText (global::Mono.Unix.Catalog.GetString ("OUTPUT"));
		this.cbDPin11.Name = "cbDPin11";
		this.cbDPin11.Active = 1;
		this.VBoxDigitalPinModes.Add (this.cbDPin11);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinModes [this.cbDPin11]));
		w24.Position = 2;
		w24.Expand = false;
		w24.Fill = false;
		// Container child VBoxDigitalPinModes.Gtk.Box+BoxChild
		this.cbDPin10 = global::Gtk.ComboBox.NewText ();
		this.cbDPin10.AppendText (global::Mono.Unix.Catalog.GetString ("INPUT"));
		this.cbDPin10.AppendText (global::Mono.Unix.Catalog.GetString ("OUTPUT"));
		this.cbDPin10.Name = "cbDPin10";
		this.cbDPin10.Active = 1;
		this.VBoxDigitalPinModes.Add (this.cbDPin10);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinModes [this.cbDPin10]));
		w25.Position = 3;
		w25.Expand = false;
		w25.Fill = false;
		// Container child VBoxDigitalPinModes.Gtk.Box+BoxChild
		this.cbDPin9 = global::Gtk.ComboBox.NewText ();
		this.cbDPin9.AppendText (global::Mono.Unix.Catalog.GetString ("INPUT"));
		this.cbDPin9.AppendText (global::Mono.Unix.Catalog.GetString ("OUTPUT"));
		this.cbDPin9.Name = "cbDPin9";
		this.cbDPin9.Active = 1;
		this.VBoxDigitalPinModes.Add (this.cbDPin9);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinModes [this.cbDPin9]));
		w26.Position = 4;
		w26.Expand = false;
		w26.Fill = false;
		// Container child VBoxDigitalPinModes.Gtk.Box+BoxChild
		this.cbDPin8 = global::Gtk.ComboBox.NewText ();
		this.cbDPin8.AppendText (global::Mono.Unix.Catalog.GetString ("INPUT"));
		this.cbDPin8.AppendText (global::Mono.Unix.Catalog.GetString ("OUTPUT"));
		this.cbDPin8.Name = "cbDPin8";
		this.cbDPin8.Active = 1;
		this.VBoxDigitalPinModes.Add (this.cbDPin8);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinModes [this.cbDPin8]));
		w27.Position = 5;
		w27.Expand = false;
		w27.Fill = false;
		// Container child VBoxDigitalPinModes.Gtk.Box+BoxChild
		this.cbDPin7 = global::Gtk.ComboBox.NewText ();
		this.cbDPin7.AppendText (global::Mono.Unix.Catalog.GetString ("INPUT"));
		this.cbDPin7.AppendText (global::Mono.Unix.Catalog.GetString ("OUTPUT"));
		this.cbDPin7.Name = "cbDPin7";
		this.cbDPin7.Active = 1;
		this.VBoxDigitalPinModes.Add (this.cbDPin7);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinModes [this.cbDPin7]));
		w28.Position = 6;
		w28.Expand = false;
		w28.Fill = false;
		// Container child VBoxDigitalPinModes.Gtk.Box+BoxChild
		this.cbDPin6 = global::Gtk.ComboBox.NewText ();
		this.cbDPin6.AppendText (global::Mono.Unix.Catalog.GetString ("INPUT"));
		this.cbDPin6.AppendText (global::Mono.Unix.Catalog.GetString ("OUTPUT"));
		this.cbDPin6.Name = "cbDPin6";
		this.cbDPin6.Active = 1;
		this.VBoxDigitalPinModes.Add (this.cbDPin6);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinModes [this.cbDPin6]));
		w29.Position = 7;
		w29.Expand = false;
		w29.Fill = false;
		// Container child VBoxDigitalPinModes.Gtk.Box+BoxChild
		this.cbDPin5 = global::Gtk.ComboBox.NewText ();
		this.cbDPin5.AppendText (global::Mono.Unix.Catalog.GetString ("INPUT"));
		this.cbDPin5.AppendText (global::Mono.Unix.Catalog.GetString ("OUTPUT"));
		this.cbDPin5.Name = "cbDPin5";
		this.cbDPin5.Active = 1;
		this.VBoxDigitalPinModes.Add (this.cbDPin5);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinModes [this.cbDPin5]));
		w30.Position = 8;
		w30.Expand = false;
		w30.Fill = false;
		// Container child VBoxDigitalPinModes.Gtk.Box+BoxChild
		this.cbDPin4 = global::Gtk.ComboBox.NewText ();
		this.cbDPin4.AppendText (global::Mono.Unix.Catalog.GetString ("INPUT"));
		this.cbDPin4.AppendText (global::Mono.Unix.Catalog.GetString ("OUTPUT"));
		this.cbDPin4.Name = "cbDPin4";
		this.cbDPin4.Active = 1;
		this.VBoxDigitalPinModes.Add (this.cbDPin4);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinModes [this.cbDPin4]));
		w31.Position = 9;
		w31.Expand = false;
		w31.Fill = false;
		// Container child VBoxDigitalPinModes.Gtk.Box+BoxChild
		this.cbDPin3 = global::Gtk.ComboBox.NewText ();
		this.cbDPin3.AppendText (global::Mono.Unix.Catalog.GetString ("INPUT"));
		this.cbDPin3.AppendText (global::Mono.Unix.Catalog.GetString ("OUTPUT"));
		this.cbDPin3.Name = "cbDPin3";
		this.cbDPin3.Active = 1;
		this.VBoxDigitalPinModes.Add (this.cbDPin3);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinModes [this.cbDPin3]));
		w32.Position = 10;
		w32.Expand = false;
		w32.Fill = false;
		// Container child VBoxDigitalPinModes.Gtk.Box+BoxChild
		this.cbDPin2 = global::Gtk.ComboBox.NewText ();
		this.cbDPin2.AppendText (global::Mono.Unix.Catalog.GetString ("INPUT"));
		this.cbDPin2.AppendText (global::Mono.Unix.Catalog.GetString ("OUTPUT"));
		this.cbDPin2.Name = "cbDPin2";
		this.cbDPin2.Active = 1;
		this.VBoxDigitalPinModes.Add (this.cbDPin2);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinModes [this.cbDPin2]));
		w33.Position = 11;
		w33.Expand = false;
		w33.Fill = false;
		// Container child VBoxDigitalPinModes.Gtk.Box+BoxChild
		this.cbDPin1 = global::Gtk.ComboBox.NewText ();
		this.cbDPin1.AppendText (global::Mono.Unix.Catalog.GetString ("INPUT"));
		this.cbDPin1.AppendText (global::Mono.Unix.Catalog.GetString ("OUTPUT"));
		this.cbDPin1.Name = "cbDPin1";
		this.cbDPin1.Active = 1;
		this.VBoxDigitalPinModes.Add (this.cbDPin1);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinModes [this.cbDPin1]));
		w34.Position = 12;
		w34.Expand = false;
		w34.Fill = false;
		// Container child VBoxDigitalPinModes.Gtk.Box+BoxChild
		this.cbDPin = global::Gtk.ComboBox.NewText ();
		this.cbDPin.AppendText (global::Mono.Unix.Catalog.GetString ("INPUT"));
		this.cbDPin.AppendText (global::Mono.Unix.Catalog.GetString ("OUTPUT"));
		this.cbDPin.Name = "cbDPin";
		this.cbDPin.Active = 1;
		this.VBoxDigitalPinModes.Add (this.cbDPin);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinModes [this.cbDPin]));
		w35.Position = 13;
		w35.Expand = false;
		w35.Fill = false;
		this.HBoxControll.Add (this.VBoxDigitalPinModes);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.HBoxControll [this.VBoxDigitalPinModes]));
		w36.Position = 1;
		w36.Expand = false;
		w36.Fill = false;
		// Container child HBoxControll.Gtk.Box+BoxChild
		this.VBoxDigitalPinStates = new global::Gtk.VBox ();
		this.VBoxDigitalPinStates.Name = "VBoxDigitalPinStates";
		this.VBoxDigitalPinStates.Homogeneous = true;
		this.VBoxDigitalPinStates.Spacing = 6;
		// Container child VBoxDigitalPinStates.Gtk.Box+BoxChild
		this.cbtnDPin13 = new global::Gtk.CheckButton ();
		this.cbtnDPin13.CanFocus = true;
		this.cbtnDPin13.Name = "cbtnDPin13";
		this.cbtnDPin13.Label = global::Mono.Unix.Catalog.GetString ("On");
		this.cbtnDPin13.DrawIndicator = true;
		this.cbtnDPin13.UseUnderline = true;
		this.VBoxDigitalPinStates.Add (this.cbtnDPin13);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinStates [this.cbtnDPin13]));
		w37.Position = 0;
		w37.Expand = false;
		w37.Fill = false;
		// Container child VBoxDigitalPinStates.Gtk.Box+BoxChild
		this.cbtnDPin12 = new global::Gtk.CheckButton ();
		this.cbtnDPin12.CanFocus = true;
		this.cbtnDPin12.Name = "cbtnDPin12";
		this.cbtnDPin12.Label = global::Mono.Unix.Catalog.GetString ("On");
		this.cbtnDPin12.DrawIndicator = true;
		this.cbtnDPin12.UseUnderline = true;
		this.VBoxDigitalPinStates.Add (this.cbtnDPin12);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinStates [this.cbtnDPin12]));
		w38.Position = 1;
		w38.Expand = false;
		w38.Fill = false;
		// Container child VBoxDigitalPinStates.Gtk.Box+BoxChild
		this.cbtnDPin11 = new global::Gtk.CheckButton ();
		this.cbtnDPin11.CanFocus = true;
		this.cbtnDPin11.Name = "cbtnDPin11";
		this.cbtnDPin11.Label = global::Mono.Unix.Catalog.GetString ("On");
		this.cbtnDPin11.DrawIndicator = true;
		this.cbtnDPin11.UseUnderline = true;
		this.VBoxDigitalPinStates.Add (this.cbtnDPin11);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinStates [this.cbtnDPin11]));
		w39.Position = 2;
		w39.Expand = false;
		w39.Fill = false;
		// Container child VBoxDigitalPinStates.Gtk.Box+BoxChild
		this.cbtnDPin10 = new global::Gtk.CheckButton ();
		this.cbtnDPin10.CanFocus = true;
		this.cbtnDPin10.Name = "cbtnDPin10";
		this.cbtnDPin10.Label = global::Mono.Unix.Catalog.GetString ("On");
		this.cbtnDPin10.DrawIndicator = true;
		this.cbtnDPin10.UseUnderline = true;
		this.VBoxDigitalPinStates.Add (this.cbtnDPin10);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinStates [this.cbtnDPin10]));
		w40.Position = 3;
		w40.Expand = false;
		w40.Fill = false;
		// Container child VBoxDigitalPinStates.Gtk.Box+BoxChild
		this.cbtnDPin9 = new global::Gtk.CheckButton ();
		this.cbtnDPin9.CanFocus = true;
		this.cbtnDPin9.Name = "cbtnDPin9";
		this.cbtnDPin9.Label = global::Mono.Unix.Catalog.GetString ("On");
		this.cbtnDPin9.DrawIndicator = true;
		this.cbtnDPin9.UseUnderline = true;
		this.VBoxDigitalPinStates.Add (this.cbtnDPin9);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinStates [this.cbtnDPin9]));
		w41.Position = 4;
		w41.Expand = false;
		w41.Fill = false;
		// Container child VBoxDigitalPinStates.Gtk.Box+BoxChild
		this.cbtnDPin8 = new global::Gtk.CheckButton ();
		this.cbtnDPin8.CanFocus = true;
		this.cbtnDPin8.Name = "cbtnDPin8";
		this.cbtnDPin8.Label = global::Mono.Unix.Catalog.GetString ("On");
		this.cbtnDPin8.DrawIndicator = true;
		this.cbtnDPin8.UseUnderline = true;
		this.VBoxDigitalPinStates.Add (this.cbtnDPin8);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinStates [this.cbtnDPin8]));
		w42.Position = 5;
		w42.Expand = false;
		w42.Fill = false;
		// Container child VBoxDigitalPinStates.Gtk.Box+BoxChild
		this.cbtnDPin = new global::Gtk.CheckButton ();
		this.cbtnDPin.CanFocus = true;
		this.cbtnDPin.Name = "cbtnDPin";
		this.cbtnDPin.Label = global::Mono.Unix.Catalog.GetString ("On");
		this.cbtnDPin.DrawIndicator = true;
		this.cbtnDPin.UseUnderline = true;
		this.VBoxDigitalPinStates.Add (this.cbtnDPin);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinStates [this.cbtnDPin]));
		w43.PackType = ((global::Gtk.PackType)(1));
		w43.Position = 6;
		w43.Expand = false;
		w43.Fill = false;
		// Container child VBoxDigitalPinStates.Gtk.Box+BoxChild
		this.cbtnDPin1 = new global::Gtk.CheckButton ();
		this.cbtnDPin1.CanFocus = true;
		this.cbtnDPin1.Name = "cbtnDPin1";
		this.cbtnDPin1.Label = global::Mono.Unix.Catalog.GetString ("On");
		this.cbtnDPin1.DrawIndicator = true;
		this.cbtnDPin1.UseUnderline = true;
		this.VBoxDigitalPinStates.Add (this.cbtnDPin1);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinStates [this.cbtnDPin1]));
		w44.PackType = ((global::Gtk.PackType)(1));
		w44.Position = 7;
		w44.Expand = false;
		w44.Fill = false;
		// Container child VBoxDigitalPinStates.Gtk.Box+BoxChild
		this.cbtnDPin2 = new global::Gtk.CheckButton ();
		this.cbtnDPin2.CanFocus = true;
		this.cbtnDPin2.Name = "cbtnDPin2";
		this.cbtnDPin2.Label = global::Mono.Unix.Catalog.GetString ("On");
		this.cbtnDPin2.DrawIndicator = true;
		this.cbtnDPin2.UseUnderline = true;
		this.VBoxDigitalPinStates.Add (this.cbtnDPin2);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinStates [this.cbtnDPin2]));
		w45.PackType = ((global::Gtk.PackType)(1));
		w45.Position = 8;
		w45.Expand = false;
		w45.Fill = false;
		// Container child VBoxDigitalPinStates.Gtk.Box+BoxChild
		this.cbtnDPin3 = new global::Gtk.CheckButton ();
		this.cbtnDPin3.CanFocus = true;
		this.cbtnDPin3.Name = "cbtnDPin3";
		this.cbtnDPin3.Label = global::Mono.Unix.Catalog.GetString ("On");
		this.cbtnDPin3.DrawIndicator = true;
		this.cbtnDPin3.UseUnderline = true;
		this.VBoxDigitalPinStates.Add (this.cbtnDPin3);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinStates [this.cbtnDPin3]));
		w46.PackType = ((global::Gtk.PackType)(1));
		w46.Position = 9;
		w46.Expand = false;
		w46.Fill = false;
		// Container child VBoxDigitalPinStates.Gtk.Box+BoxChild
		this.cbtnDPin4 = new global::Gtk.CheckButton ();
		this.cbtnDPin4.CanFocus = true;
		this.cbtnDPin4.Name = "cbtnDPin4";
		this.cbtnDPin4.Label = global::Mono.Unix.Catalog.GetString ("On");
		this.cbtnDPin4.DrawIndicator = true;
		this.cbtnDPin4.UseUnderline = true;
		this.VBoxDigitalPinStates.Add (this.cbtnDPin4);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinStates [this.cbtnDPin4]));
		w47.PackType = ((global::Gtk.PackType)(1));
		w47.Position = 10;
		w47.Expand = false;
		w47.Fill = false;
		// Container child VBoxDigitalPinStates.Gtk.Box+BoxChild
		this.cbtnDPin5 = new global::Gtk.CheckButton ();
		this.cbtnDPin5.CanFocus = true;
		this.cbtnDPin5.Name = "cbtnDPin5";
		this.cbtnDPin5.Label = global::Mono.Unix.Catalog.GetString ("On");
		this.cbtnDPin5.DrawIndicator = true;
		this.cbtnDPin5.UseUnderline = true;
		this.VBoxDigitalPinStates.Add (this.cbtnDPin5);
		global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinStates [this.cbtnDPin5]));
		w48.PackType = ((global::Gtk.PackType)(1));
		w48.Position = 11;
		w48.Expand = false;
		w48.Fill = false;
		// Container child VBoxDigitalPinStates.Gtk.Box+BoxChild
		this.cbtnDPin6 = new global::Gtk.CheckButton ();
		this.cbtnDPin6.CanFocus = true;
		this.cbtnDPin6.Name = "cbtnDPin6";
		this.cbtnDPin6.Label = global::Mono.Unix.Catalog.GetString ("On");
		this.cbtnDPin6.DrawIndicator = true;
		this.cbtnDPin6.UseUnderline = true;
		this.VBoxDigitalPinStates.Add (this.cbtnDPin6);
		global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinStates [this.cbtnDPin6]));
		w49.PackType = ((global::Gtk.PackType)(1));
		w49.Position = 12;
		w49.Expand = false;
		w49.Fill = false;
		// Container child VBoxDigitalPinStates.Gtk.Box+BoxChild
		this.cbtnDPin7 = new global::Gtk.CheckButton ();
		this.cbtnDPin7.CanFocus = true;
		this.cbtnDPin7.Name = "cbtnDPin7";
		this.cbtnDPin7.Label = global::Mono.Unix.Catalog.GetString ("On");
		this.cbtnDPin7.DrawIndicator = true;
		this.cbtnDPin7.UseUnderline = true;
		this.VBoxDigitalPinStates.Add (this.cbtnDPin7);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.VBoxDigitalPinStates [this.cbtnDPin7]));
		w50.PackType = ((global::Gtk.PackType)(1));
		w50.Position = 13;
		w50.Expand = false;
		w50.Fill = false;
		this.HBoxControll.Add (this.VBoxDigitalPinStates);
		global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.HBoxControll [this.VBoxDigitalPinStates]));
		w51.Position = 2;
		w51.Expand = false;
		// Container child HBoxControll.Gtk.Box+BoxChild
		this.vseparator1 = new global::Gtk.VSeparator ();
		this.vseparator1.Name = "vseparator1";
		this.HBoxControll.Add (this.vseparator1);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.HBoxControll [this.vseparator1]));
		w52.Position = 3;
		w52.Expand = false;
		w52.Fill = false;
		// Container child HBoxControll.Gtk.Box+BoxChild
		this.VBoxAnalogPinNames = new global::Gtk.VBox ();
		this.VBoxAnalogPinNames.Name = "VBoxAnalogPinNames";
		this.VBoxAnalogPinNames.Homogeneous = true;
		this.VBoxAnalogPinNames.Spacing = 6;
		// Container child VBoxAnalogPinNames.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Analog Pins");
		this.VBoxAnalogPinNames.Add (this.label1);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.VBoxAnalogPinNames [this.label1]));
		w53.Position = 0;
		w53.Expand = false;
		w53.Fill = false;
		// Container child VBoxAnalogPinNames.Gtk.Box+BoxChild
		this.LabelA5 = new global::Gtk.Label ();
		this.LabelA5.Name = "LabelA5";
		this.LabelA5.LabelProp = global::Mono.Unix.Catalog.GetString ("A5:");
		this.VBoxAnalogPinNames.Add (this.LabelA5);
		global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.VBoxAnalogPinNames [this.LabelA5]));
		w54.Position = 1;
		w54.Expand = false;
		w54.Fill = false;
		// Container child VBoxAnalogPinNames.Gtk.Box+BoxChild
		this.LabelA4 = new global::Gtk.Label ();
		this.LabelA4.Name = "LabelA4";
		this.LabelA4.LabelProp = global::Mono.Unix.Catalog.GetString ("A4:");
		this.VBoxAnalogPinNames.Add (this.LabelA4);
		global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.VBoxAnalogPinNames [this.LabelA4]));
		w55.Position = 2;
		w55.Expand = false;
		w55.Fill = false;
		// Container child VBoxAnalogPinNames.Gtk.Box+BoxChild
		this.LabelA3 = new global::Gtk.Label ();
		this.LabelA3.Name = "LabelA3";
		this.LabelA3.LabelProp = global::Mono.Unix.Catalog.GetString ("A3:");
		this.VBoxAnalogPinNames.Add (this.LabelA3);
		global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.VBoxAnalogPinNames [this.LabelA3]));
		w56.Position = 3;
		w56.Expand = false;
		w56.Fill = false;
		// Container child VBoxAnalogPinNames.Gtk.Box+BoxChild
		this.LabelA = new global::Gtk.Label ();
		this.LabelA.Name = "LabelA";
		this.LabelA.LabelProp = global::Mono.Unix.Catalog.GetString ("A0:");
		this.VBoxAnalogPinNames.Add (this.LabelA);
		global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.VBoxAnalogPinNames [this.LabelA]));
		w57.PackType = ((global::Gtk.PackType)(1));
		w57.Position = 4;
		w57.Expand = false;
		w57.Fill = false;
		// Container child VBoxAnalogPinNames.Gtk.Box+BoxChild
		this.LabelA1 = new global::Gtk.Label ();
		this.LabelA1.Name = "LabelA1";
		this.LabelA1.LabelProp = global::Mono.Unix.Catalog.GetString ("A1:");
		this.VBoxAnalogPinNames.Add (this.LabelA1);
		global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.VBoxAnalogPinNames [this.LabelA1]));
		w58.PackType = ((global::Gtk.PackType)(1));
		w58.Position = 5;
		w58.Expand = false;
		w58.Fill = false;
		// Container child VBoxAnalogPinNames.Gtk.Box+BoxChild
		this.LabelA2 = new global::Gtk.Label ();
		this.LabelA2.Name = "LabelA2";
		this.LabelA2.LabelProp = global::Mono.Unix.Catalog.GetString ("A2:");
		this.VBoxAnalogPinNames.Add (this.LabelA2);
		global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.VBoxAnalogPinNames [this.LabelA2]));
		w59.PackType = ((global::Gtk.PackType)(1));
		w59.Position = 6;
		w59.Expand = false;
		w59.Fill = false;
		this.HBoxControll.Add (this.VBoxAnalogPinNames);
		global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.HBoxControll [this.VBoxAnalogPinNames]));
		w60.Position = 4;
		w60.Expand = false;
		w60.Fill = false;
		w60.Padding = ((uint)(5));
		// Container child HBoxControll.Gtk.Box+BoxChild
		this.VBoxAnalogPinModes = new global::Gtk.VBox ();
		this.VBoxAnalogPinModes.Name = "VBoxAnalogPinModes";
		this.VBoxAnalogPinModes.Homogeneous = true;
		this.VBoxAnalogPinModes.Spacing = 6;
		// Container child VBoxAnalogPinModes.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Pin Mode");
		this.VBoxAnalogPinModes.Add (this.label2);
		global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.VBoxAnalogPinModes [this.label2]));
		w61.Position = 0;
		w61.Expand = false;
		w61.Fill = false;
		// Container child VBoxAnalogPinModes.Gtk.Box+BoxChild
		this.CBAnalogPin5Mode = global::Gtk.ComboBox.NewText ();
		this.CBAnalogPin5Mode.AppendText (global::Mono.Unix.Catalog.GetString ("INPUT"));
		this.CBAnalogPin5Mode.AppendText (global::Mono.Unix.Catalog.GetString ("OUTPUT"));
		this.CBAnalogPin5Mode.Name = "CBAnalogPin5Mode";
		this.CBAnalogPin5Mode.Active = 0;
		this.VBoxAnalogPinModes.Add (this.CBAnalogPin5Mode);
		global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.VBoxAnalogPinModes [this.CBAnalogPin5Mode]));
		w62.Position = 1;
		w62.Expand = false;
		w62.Fill = false;
		// Container child VBoxAnalogPinModes.Gtk.Box+BoxChild
		this.combobox16 = global::Gtk.ComboBox.NewText ();
		this.combobox16.AppendText (global::Mono.Unix.Catalog.GetString ("INPUT"));
		this.combobox16.AppendText (global::Mono.Unix.Catalog.GetString ("OUTPUT"));
		this.combobox16.Name = "combobox16";
		this.combobox16.Active = 0;
		this.VBoxAnalogPinModes.Add (this.combobox16);
		global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.VBoxAnalogPinModes [this.combobox16]));
		w63.Position = 2;
		w63.Expand = false;
		w63.Fill = false;
		// Container child VBoxAnalogPinModes.Gtk.Box+BoxChild
		this.combobox17 = global::Gtk.ComboBox.NewText ();
		this.combobox17.AppendText (global::Mono.Unix.Catalog.GetString ("INPUT"));
		this.combobox17.AppendText (global::Mono.Unix.Catalog.GetString ("OUTPUT"));
		this.combobox17.Name = "combobox17";
		this.combobox17.Active = 0;
		this.VBoxAnalogPinModes.Add (this.combobox17);
		global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.VBoxAnalogPinModes [this.combobox17]));
		w64.Position = 3;
		w64.Expand = false;
		w64.Fill = false;
		// Container child VBoxAnalogPinModes.Gtk.Box+BoxChild
		this.combobox18 = global::Gtk.ComboBox.NewText ();
		this.combobox18.AppendText (global::Mono.Unix.Catalog.GetString ("INPUT"));
		this.combobox18.AppendText (global::Mono.Unix.Catalog.GetString ("OUTPUT"));
		this.combobox18.Name = "combobox18";
		this.combobox18.Active = 0;
		this.VBoxAnalogPinModes.Add (this.combobox18);
		global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.VBoxAnalogPinModes [this.combobox18]));
		w65.Position = 4;
		w65.Expand = false;
		w65.Fill = false;
		// Container child VBoxAnalogPinModes.Gtk.Box+BoxChild
		this.combobox20 = global::Gtk.ComboBox.NewText ();
		this.combobox20.AppendText (global::Mono.Unix.Catalog.GetString ("INPUT"));
		this.combobox20.AppendText (global::Mono.Unix.Catalog.GetString ("OUTPUT"));
		this.combobox20.Name = "combobox20";
		this.combobox20.Active = 0;
		this.VBoxAnalogPinModes.Add (this.combobox20);
		global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.VBoxAnalogPinModes [this.combobox20]));
		w66.Position = 5;
		w66.Expand = false;
		w66.Fill = false;
		// Container child VBoxAnalogPinModes.Gtk.Box+BoxChild
		this.CBAnalogPin0Mode = global::Gtk.ComboBox.NewText ();
		this.CBAnalogPin0Mode.AppendText (global::Mono.Unix.Catalog.GetString ("INPUT"));
		this.CBAnalogPin0Mode.AppendText (global::Mono.Unix.Catalog.GetString ("OUTPUT"));
		this.CBAnalogPin0Mode.Name = "CBAnalogPin0Mode";
		this.CBAnalogPin0Mode.Active = 0;
		this.VBoxAnalogPinModes.Add (this.CBAnalogPin0Mode);
		global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.VBoxAnalogPinModes [this.CBAnalogPin0Mode]));
		w67.Position = 6;
		w67.Expand = false;
		w67.Fill = false;
		this.HBoxControll.Add (this.VBoxAnalogPinModes);
		global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.HBoxControll [this.VBoxAnalogPinModes]));
		w68.Position = 5;
		w68.Expand = false;
		w68.Fill = false;
		// Container child HBoxControll.Gtk.Box+BoxChild
		this.VBoxAnalogValues = new global::Gtk.VBox ();
		this.VBoxAnalogValues.WidthRequest = 104;
		this.VBoxAnalogValues.Name = "VBoxAnalogValues";
		this.VBoxAnalogValues.Homogeneous = true;
		this.VBoxAnalogValues.Spacing = 6;
		// Container child VBoxAnalogValues.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Pin Intput Value");
		this.VBoxAnalogValues.Add (this.label3);
		global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.VBoxAnalogValues [this.label3]));
		w69.Position = 0;
		w69.Expand = false;
		w69.Fill = false;
		// Container child VBoxAnalogValues.Gtk.Box+BoxChild
		this.LabelValueA5 = new global::Gtk.Label ();
		this.LabelValueA5.Name = "LabelValueA5";
		this.LabelValueA5.Xalign = 1F;
		this.LabelValueA5.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
		this.LabelValueA5.Justify = ((global::Gtk.Justification)(1));
		this.VBoxAnalogValues.Add (this.LabelValueA5);
		global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.VBoxAnalogValues [this.LabelValueA5]));
		w70.Position = 1;
		w70.Expand = false;
		w70.Fill = false;
		// Container child VBoxAnalogValues.Gtk.Box+BoxChild
		this.LabelValueA4 = new global::Gtk.Label ();
		this.LabelValueA4.Name = "LabelValueA4";
		this.LabelValueA4.Xalign = 1F;
		this.LabelValueA4.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
		this.LabelValueA4.Justify = ((global::Gtk.Justification)(1));
		this.VBoxAnalogValues.Add (this.LabelValueA4);
		global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.VBoxAnalogValues [this.LabelValueA4]));
		w71.Position = 2;
		w71.Expand = false;
		w71.Fill = false;
		// Container child VBoxAnalogValues.Gtk.Box+BoxChild
		this.LabelValueA3 = new global::Gtk.Label ();
		this.LabelValueA3.Name = "LabelValueA3";
		this.LabelValueA3.Xalign = 1F;
		this.LabelValueA3.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
		this.LabelValueA3.Justify = ((global::Gtk.Justification)(1));
		this.VBoxAnalogValues.Add (this.LabelValueA3);
		global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.VBoxAnalogValues [this.LabelValueA3]));
		w72.Position = 3;
		w72.Expand = false;
		w72.Fill = false;
		// Container child VBoxAnalogValues.Gtk.Box+BoxChild
		this.LabelValueA = new global::Gtk.Label ();
		this.LabelValueA.Name = "LabelValueA";
		this.LabelValueA.Xalign = 1F;
		this.LabelValueA.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
		this.LabelValueA.Justify = ((global::Gtk.Justification)(1));
		this.VBoxAnalogValues.Add (this.LabelValueA);
		global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.VBoxAnalogValues [this.LabelValueA]));
		w73.PackType = ((global::Gtk.PackType)(1));
		w73.Position = 4;
		w73.Expand = false;
		w73.Fill = false;
		// Container child VBoxAnalogValues.Gtk.Box+BoxChild
		this.LabelValueA1 = new global::Gtk.Label ();
		this.LabelValueA1.Name = "LabelValueA1";
		this.LabelValueA1.Xalign = 1F;
		this.LabelValueA1.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
		this.LabelValueA1.Justify = ((global::Gtk.Justification)(1));
		this.VBoxAnalogValues.Add (this.LabelValueA1);
		global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.VBoxAnalogValues [this.LabelValueA1]));
		w74.PackType = ((global::Gtk.PackType)(1));
		w74.Position = 5;
		w74.Expand = false;
		w74.Fill = false;
		// Container child VBoxAnalogValues.Gtk.Box+BoxChild
		this.LabelValueA2 = new global::Gtk.Label ();
		this.LabelValueA2.Name = "LabelValueA2";
		this.LabelValueA2.Xalign = 1F;
		this.LabelValueA2.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
		this.LabelValueA2.Justify = ((global::Gtk.Justification)(1));
		this.VBoxAnalogValues.Add (this.LabelValueA2);
		global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.VBoxAnalogValues [this.LabelValueA2]));
		w75.PackType = ((global::Gtk.PackType)(1));
		w75.Position = 6;
		w75.Expand = false;
		w75.Fill = false;
		this.HBoxControll.Add (this.VBoxAnalogValues);
		global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.HBoxControll [this.VBoxAnalogValues]));
		w76.Position = 6;
		w76.Expand = false;
		w76.Fill = false;
		// Container child HBoxControll.Gtk.Box+BoxChild
		this.VBoxAnalogPinOutput = new global::Gtk.VBox ();
		this.VBoxAnalogPinOutput.Name = "VBoxAnalogPinOutput";
		this.VBoxAnalogPinOutput.Homogeneous = true;
		this.VBoxAnalogPinOutput.Spacing = 6;
		// Container child VBoxAnalogPinOutput.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Pin Output Value");
		this.VBoxAnalogPinOutput.Add (this.label4);
		global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.VBoxAnalogPinOutput [this.label4]));
		w77.Position = 0;
		w77.Expand = false;
		w77.Fill = false;
		// Container child VBoxAnalogPinOutput.Gtk.Box+BoxChild
		this.HScaleAnalogPinFive = new global::Gtk.HScale (null);
		this.HScaleAnalogPinFive.CanFocus = true;
		this.HScaleAnalogPinFive.Name = "HScaleAnalogPinFive";
		this.HScaleAnalogPinFive.Adjustment.Upper = 1023;
		this.HScaleAnalogPinFive.Adjustment.PageIncrement = 1;
		this.HScaleAnalogPinFive.Adjustment.StepIncrement = 1;
		this.HScaleAnalogPinFive.DrawValue = true;
		this.HScaleAnalogPinFive.Digits = 0;
		this.HScaleAnalogPinFive.ValuePos = ((global::Gtk.PositionType)(2));
		this.VBoxAnalogPinOutput.Add (this.HScaleAnalogPinFive);
		global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.VBoxAnalogPinOutput [this.HScaleAnalogPinFive]));
		w78.Position = 1;
		w78.Expand = false;
		w78.Fill = false;
		// Container child VBoxAnalogPinOutput.Gtk.Box+BoxChild
		this.hscale2 = new global::Gtk.HScale (null);
		this.hscale2.CanFocus = true;
		this.hscale2.Name = "hscale2";
		this.hscale2.Adjustment.Upper = 5;
		this.hscale2.Adjustment.PageIncrement = 0.1;
		this.hscale2.Adjustment.StepIncrement = 0.1;
		this.hscale2.DrawValue = true;
		this.hscale2.Digits = 0;
		this.hscale2.ValuePos = ((global::Gtk.PositionType)(2));
		this.VBoxAnalogPinOutput.Add (this.hscale2);
		global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.VBoxAnalogPinOutput [this.hscale2]));
		w79.Position = 2;
		w79.Expand = false;
		w79.Fill = false;
		// Container child VBoxAnalogPinOutput.Gtk.Box+BoxChild
		this.hscale3 = new global::Gtk.HScale (null);
		this.hscale3.CanFocus = true;
		this.hscale3.Name = "hscale3";
		this.hscale3.Adjustment.Upper = 5;
		this.hscale3.Adjustment.PageIncrement = 0.1;
		this.hscale3.Adjustment.StepIncrement = 0.1;
		this.hscale3.DrawValue = true;
		this.hscale3.Digits = 0;
		this.hscale3.ValuePos = ((global::Gtk.PositionType)(2));
		this.VBoxAnalogPinOutput.Add (this.hscale3);
		global::Gtk.Box.BoxChild w80 = ((global::Gtk.Box.BoxChild)(this.VBoxAnalogPinOutput [this.hscale3]));
		w80.Position = 3;
		w80.Expand = false;
		w80.Fill = false;
		// Container child VBoxAnalogPinOutput.Gtk.Box+BoxChild
		this.hscale4 = new global::Gtk.HScale (null);
		this.hscale4.CanFocus = true;
		this.hscale4.Name = "hscale4";
		this.hscale4.Adjustment.Upper = 5;
		this.hscale4.Adjustment.PageIncrement = 0.1;
		this.hscale4.Adjustment.StepIncrement = 0.1;
		this.hscale4.DrawValue = true;
		this.hscale4.Digits = 0;
		this.hscale4.ValuePos = ((global::Gtk.PositionType)(2));
		this.VBoxAnalogPinOutput.Add (this.hscale4);
		global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.VBoxAnalogPinOutput [this.hscale4]));
		w81.Position = 4;
		w81.Expand = false;
		w81.Fill = false;
		// Container child VBoxAnalogPinOutput.Gtk.Box+BoxChild
		this.hscale5 = new global::Gtk.HScale (null);
		this.hscale5.CanFocus = true;
		this.hscale5.Name = "hscale5";
		this.hscale5.Adjustment.Upper = 5;
		this.hscale5.Adjustment.PageIncrement = 0.1;
		this.hscale5.Adjustment.StepIncrement = 0.1;
		this.hscale5.DrawValue = true;
		this.hscale5.Digits = 0;
		this.hscale5.ValuePos = ((global::Gtk.PositionType)(2));
		this.VBoxAnalogPinOutput.Add (this.hscale5);
		global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.VBoxAnalogPinOutput [this.hscale5]));
		w82.Position = 5;
		w82.Expand = false;
		w82.Fill = false;
		// Container child VBoxAnalogPinOutput.Gtk.Box+BoxChild
		this.HScaleAnalogPinNull = new global::Gtk.HScale (null);
		this.HScaleAnalogPinNull.CanFocus = true;
		this.HScaleAnalogPinNull.Name = "HScaleAnalogPinNull";
		this.HScaleAnalogPinNull.Adjustment.Upper = 1023;
		this.HScaleAnalogPinNull.Adjustment.PageIncrement = 1;
		this.HScaleAnalogPinNull.Adjustment.StepIncrement = 1;
		this.HScaleAnalogPinNull.DrawValue = true;
		this.HScaleAnalogPinNull.Digits = 2;
		this.HScaleAnalogPinNull.ValuePos = ((global::Gtk.PositionType)(2));
		this.VBoxAnalogPinOutput.Add (this.HScaleAnalogPinNull);
		global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(this.VBoxAnalogPinOutput [this.HScaleAnalogPinNull]));
		w83.Position = 6;
		w83.Expand = false;
		w83.Fill = false;
		this.HBoxControll.Add (this.VBoxAnalogPinOutput);
		global::Gtk.Box.BoxChild w84 = ((global::Gtk.Box.BoxChild)(this.HBoxControll [this.VBoxAnalogPinOutput]));
		w84.PackType = ((global::Gtk.PackType)(1));
		w84.Position = 7;
		w84.Expand = false;
		w84.Fill = false;
		this.nbMain.Add (this.HBoxControll);
		// Notebook tab
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Controll");
		this.nbMain.SetTabLabel (this.HBoxControll, this.label5);
		this.label5.ShowAll ();
		// Container child nbMain.Gtk.Notebook+NotebookChild
		this.table1 = new global::Gtk.Table (((uint)(1)), ((uint)(1)), true);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.tableValues = new global::Gtk.Table (((uint)(8)), ((uint)(3)), false);
		this.tableValues.Name = "tableValues";
		this.tableValues.RowSpacing = ((uint)(6));
		this.tableValues.ColumnSpacing = ((uint)(6));
		// Container child tableValues.Gtk.Table+TableChild
		this.btnDataRefreshAll = new global::Gtk.Button ();
		this.btnDataRefreshAll.CanFocus = true;
		this.btnDataRefreshAll.Name = "btnDataRefreshAll";
		this.btnDataRefreshAll.UseUnderline = true;
		this.btnDataRefreshAll.Label = global::Mono.Unix.Catalog.GetString ("Refresh ALL");
		this.tableValues.Add (this.btnDataRefreshAll);
		global::Gtk.Table.TableChild w86 = ((global::Gtk.Table.TableChild)(this.tableValues [this.btnDataRefreshAll]));
		w86.TopAttach = ((uint)(7));
		w86.BottomAttach = ((uint)(8));
		w86.RightAttach = ((uint)(3));
		w86.XOptions = ((global::Gtk.AttachOptions)(4));
		w86.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableValues.Gtk.Table+TableChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Refresh");
		this.tableValues.Add (this.button1);
		global::Gtk.Table.TableChild w87 = ((global::Gtk.Table.TableChild)(this.tableValues [this.button1]));
		w87.TopAttach = ((uint)(4));
		w87.BottomAttach = ((uint)(5));
		w87.LeftAttach = ((uint)(2));
		w87.RightAttach = ((uint)(3));
		w87.XOptions = ((global::Gtk.AttachOptions)(4));
		w87.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableValues.Gtk.Table+TableChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("Refresh");
		this.tableValues.Add (this.button2);
		global::Gtk.Table.TableChild w88 = ((global::Gtk.Table.TableChild)(this.tableValues [this.button2]));
		w88.TopAttach = ((uint)(5));
		w88.BottomAttach = ((uint)(6));
		w88.LeftAttach = ((uint)(2));
		w88.RightAttach = ((uint)(3));
		w88.XOptions = ((global::Gtk.AttachOptions)(4));
		w88.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableValues.Gtk.Table+TableChild
		this.button4 = new global::Gtk.Button ();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString ("Refresh");
		this.tableValues.Add (this.button4);
		global::Gtk.Table.TableChild w89 = ((global::Gtk.Table.TableChild)(this.tableValues [this.button4]));
		w89.LeftAttach = ((uint)(2));
		w89.RightAttach = ((uint)(3));
		w89.XOptions = ((global::Gtk.AttachOptions)(4));
		w89.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableValues.Gtk.Table+TableChild
		this.button5 = new global::Gtk.Button ();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString ("Refresh");
		this.tableValues.Add (this.button5);
		global::Gtk.Table.TableChild w90 = ((global::Gtk.Table.TableChild)(this.tableValues [this.button5]));
		w90.TopAttach = ((uint)(1));
		w90.BottomAttach = ((uint)(2));
		w90.LeftAttach = ((uint)(2));
		w90.RightAttach = ((uint)(3));
		w90.XOptions = ((global::Gtk.AttachOptions)(4));
		w90.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableValues.Gtk.Table+TableChild
		this.button6 = new global::Gtk.Button ();
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString ("Refresh");
		this.tableValues.Add (this.button6);
		global::Gtk.Table.TableChild w91 = ((global::Gtk.Table.TableChild)(this.tableValues [this.button6]));
		w91.TopAttach = ((uint)(2));
		w91.BottomAttach = ((uint)(3));
		w91.LeftAttach = ((uint)(2));
		w91.RightAttach = ((uint)(3));
		w91.XOptions = ((global::Gtk.AttachOptions)(4));
		w91.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableValues.Gtk.Table+TableChild
		this.button7 = new global::Gtk.Button ();
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString ("Refresh");
		this.tableValues.Add (this.button7);
		global::Gtk.Table.TableChild w92 = ((global::Gtk.Table.TableChild)(this.tableValues [this.button7]));
		w92.TopAttach = ((uint)(3));
		w92.BottomAttach = ((uint)(4));
		w92.LeftAttach = ((uint)(2));
		w92.RightAttach = ((uint)(3));
		w92.XOptions = ((global::Gtk.AttachOptions)(4));
		w92.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableValues.Gtk.Table+TableChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		this.tableValues.Add (this.fixed1);
		global::Gtk.Table.TableChild w93 = ((global::Gtk.Table.TableChild)(this.tableValues [this.fixed1]));
		w93.TopAttach = ((uint)(6));
		w93.BottomAttach = ((uint)(7));
		w93.RightAttach = ((uint)(3));
		// Container child tableValues.Gtk.Table+TableChild
		this.label18 = new global::Gtk.Label ();
		this.label18.Name = "label18";
		this.label18.Xalign = 0F;
		this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Version:");
		this.tableValues.Add (this.label18);
		global::Gtk.Table.TableChild w94 = ((global::Gtk.Table.TableChild)(this.tableValues [this.label18]));
		w94.XOptions = ((global::Gtk.AttachOptions)(4));
		w94.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableValues.Gtk.Table+TableChild
		this.label19 = new global::Gtk.Label ();
		this.label19.Name = "label19";
		this.label19.Xalign = 0F;
		this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Model:");
		this.tableValues.Add (this.label19);
		global::Gtk.Table.TableChild w95 = ((global::Gtk.Table.TableChild)(this.tableValues [this.label19]));
		w95.TopAttach = ((uint)(1));
		w95.BottomAttach = ((uint)(2));
		w95.XOptions = ((global::Gtk.AttachOptions)(4));
		w95.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableValues.Gtk.Table+TableChild
		this.label20 = new global::Gtk.Label ();
		this.label20.Name = "label20";
		this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("Number of digital pins:");
		this.tableValues.Add (this.label20);
		global::Gtk.Table.TableChild w96 = ((global::Gtk.Table.TableChild)(this.tableValues [this.label20]));
		w96.TopAttach = ((uint)(2));
		w96.BottomAttach = ((uint)(3));
		w96.XOptions = ((global::Gtk.AttachOptions)(4));
		w96.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableValues.Gtk.Table+TableChild
		this.label21 = new global::Gtk.Label ();
		this.label21.Name = "label21";
		this.label21.Xalign = 0F;
		this.label21.LabelProp = global::Mono.Unix.Catalog.GetString ("Number of analog pins:");
		this.tableValues.Add (this.label21);
		global::Gtk.Table.TableChild w97 = ((global::Gtk.Table.TableChild)(this.tableValues [this.label21]));
		w97.TopAttach = ((uint)(3));
		w97.BottomAttach = ((uint)(4));
		w97.XOptions = ((global::Gtk.AttachOptions)(4));
		w97.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableValues.Gtk.Table+TableChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.Xalign = 0F;
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Pin output bit mask:");
		this.tableValues.Add (this.label7);
		global::Gtk.Table.TableChild w98 = ((global::Gtk.Table.TableChild)(this.tableValues [this.label7]));
		w98.TopAttach = ((uint)(4));
		w98.BottomAttach = ((uint)(5));
		w98.XOptions = ((global::Gtk.AttachOptions)(4));
		w98.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableValues.Gtk.Table+TableChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.Xalign = 0F;
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Pin mode bit mask:");
		this.tableValues.Add (this.label8);
		global::Gtk.Table.TableChild w99 = ((global::Gtk.Table.TableChild)(this.tableValues [this.label8]));
		w99.TopAttach = ((uint)(5));
		w99.BottomAttach = ((uint)(6));
		w99.XOptions = ((global::Gtk.AttachOptions)(4));
		w99.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableValues.Gtk.Table+TableChild
		this.labelModeBitMask = new global::Gtk.Label ();
		this.labelModeBitMask.Name = "labelModeBitMask";
		this.tableValues.Add (this.labelModeBitMask);
		global::Gtk.Table.TableChild w100 = ((global::Gtk.Table.TableChild)(this.tableValues [this.labelModeBitMask]));
		w100.TopAttach = ((uint)(5));
		w100.BottomAttach = ((uint)(6));
		w100.LeftAttach = ((uint)(1));
		w100.RightAttach = ((uint)(2));
		w100.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableValues.Gtk.Table+TableChild
		this.labelModel = new global::Gtk.Label ();
		this.labelModel.Name = "labelModel";
		this.tableValues.Add (this.labelModel);
		global::Gtk.Table.TableChild w101 = ((global::Gtk.Table.TableChild)(this.tableValues [this.labelModel]));
		w101.TopAttach = ((uint)(1));
		w101.BottomAttach = ((uint)(2));
		w101.LeftAttach = ((uint)(1));
		w101.RightAttach = ((uint)(2));
		w101.XOptions = ((global::Gtk.AttachOptions)(4));
		w101.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableValues.Gtk.Table+TableChild
		this.labelNrAnaPin = new global::Gtk.Label ();
		this.labelNrAnaPin.Name = "labelNrAnaPin";
		this.tableValues.Add (this.labelNrAnaPin);
		global::Gtk.Table.TableChild w102 = ((global::Gtk.Table.TableChild)(this.tableValues [this.labelNrAnaPin]));
		w102.TopAttach = ((uint)(3));
		w102.BottomAttach = ((uint)(4));
		w102.LeftAttach = ((uint)(1));
		w102.RightAttach = ((uint)(2));
		w102.XOptions = ((global::Gtk.AttachOptions)(4));
		w102.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableValues.Gtk.Table+TableChild
		this.labelNrDigiPin = new global::Gtk.Label ();
		this.labelNrDigiPin.Name = "labelNrDigiPin";
		this.tableValues.Add (this.labelNrDigiPin);
		global::Gtk.Table.TableChild w103 = ((global::Gtk.Table.TableChild)(this.tableValues [this.labelNrDigiPin]));
		w103.TopAttach = ((uint)(2));
		w103.BottomAttach = ((uint)(3));
		w103.LeftAttach = ((uint)(1));
		w103.RightAttach = ((uint)(2));
		w103.XOptions = ((global::Gtk.AttachOptions)(4));
		w103.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableValues.Gtk.Table+TableChild
		this.labelOutputBitMask = new global::Gtk.Label ();
		this.labelOutputBitMask.Name = "labelOutputBitMask";
		this.tableValues.Add (this.labelOutputBitMask);
		global::Gtk.Table.TableChild w104 = ((global::Gtk.Table.TableChild)(this.tableValues [this.labelOutputBitMask]));
		w104.TopAttach = ((uint)(4));
		w104.BottomAttach = ((uint)(5));
		w104.LeftAttach = ((uint)(1));
		w104.RightAttach = ((uint)(2));
		w104.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableValues.Gtk.Table+TableChild
		this.labelVersion = new global::Gtk.Label ();
		this.labelVersion.Name = "labelVersion";
		this.tableValues.Add (this.labelVersion);
		global::Gtk.Table.TableChild w105 = ((global::Gtk.Table.TableChild)(this.tableValues [this.labelVersion]));
		w105.LeftAttach = ((uint)(1));
		w105.RightAttach = ((uint)(2));
		w105.XOptions = ((global::Gtk.AttachOptions)(4));
		w105.YOptions = ((global::Gtk.AttachOptions)(4));
		this.table1.Add (this.tableValues);
		this.nbMain.Add (this.table1);
		global::Gtk.Notebook.NotebookChild w107 = ((global::Gtk.Notebook.NotebookChild)(this.nbMain [this.table1]));
		w107.Position = 1;
		// Notebook tab
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Intel");
		this.nbMain.SetTabLabel (this.table1, this.label6);
		this.label6.ShowAll ();
		this.vbox3.Add (this.nbMain);
		global::Gtk.Box.BoxChild w108 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.nbMain]));
		w108.Position = 1;
		w108.Expand = false;
		w108.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.LabelStatus = new global::Gtk.Label ();
		this.LabelStatus.Name = "LabelStatus";
		this.LabelStatus.LabelProp = global::Mono.Unix.Catalog.GetString ("Status:");
		this.statusbar1.Add (this.LabelStatus);
		global::Gtk.Box.BoxChild w109 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.LabelStatus]));
		w109.Position = 1;
		w109.Expand = false;
		w109.Fill = false;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.LabelConnectionStatus = new global::Gtk.Label ();
		this.LabelConnectionStatus.Name = "LabelConnectionStatus";
		this.LabelConnectionStatus.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Not</b> connected");
		this.LabelConnectionStatus.UseMarkup = true;
		this.statusbar1.Add (this.LabelConnectionStatus);
		global::Gtk.Box.BoxChild w110 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.LabelConnectionStatus]));
		w110.Position = 2;
		w110.Expand = false;
		w110.Fill = false;
		this.vbox3.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w111 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.statusbar1]));
		w111.Position = 2;
		w111.Expand = false;
		w111.Fill = false;
		this.Add (this.vbox3);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 773;
		this.DefaultHeight = 568;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.BtnConnect.Clicked += new global::System.EventHandler (this.Connect);
		this.BtnConnectRefresh.Clicked += new global::System.EventHandler (this.OnBtnConnectRefreshClicked);
		this.cbDPin13.Changed += new global::System.EventHandler (this.OnCbDPin13Changed);
		this.cbDPin12.Changed += new global::System.EventHandler (this.OnCbDPin12Changed);
		this.cbDPin11.Changed += new global::System.EventHandler (this.OnCbDPin11Changed);
		this.cbDPin10.Changed += new global::System.EventHandler (this.OnCbDPin10Changed);
		this.cbDPin9.Changed += new global::System.EventHandler (this.OnCbDPin9Changed);
		this.cbDPin8.Changed += new global::System.EventHandler (this.OnCbDPin8Changed);
		this.cbDPin7.Changed += new global::System.EventHandler (this.OnCbDPin7Changed);
		this.cbDPin6.Changed += new global::System.EventHandler (this.OnCbDPin6Changed);
		this.cbDPin5.Changed += new global::System.EventHandler (this.OnCbDPin5Changed);
		this.cbDPin4.Changed += new global::System.EventHandler (this.OnCbDPin4Changed);
		this.cbDPin3.Changed += new global::System.EventHandler (this.OnCbDPin3Changed);
		this.cbDPin2.Changed += new global::System.EventHandler (this.OnCbDPin2Changed);
		this.cbDPin1.Changed += new global::System.EventHandler (this.OnCbDPin1Changed);
		this.cbDPin.Changed += new global::System.EventHandler (this.OnCbDPinChanged);
		this.cbtnDPin13.Toggled += new global::System.EventHandler (this.OnCheckbutton1Toggled);
		this.cbtnDPin12.Toggled += new global::System.EventHandler (this.OnCbtnDPin12Toggled);
		this.cbtnDPin11.Toggled += new global::System.EventHandler (this.OnCbtnDPin11Toggled);
		this.cbtnDPin10.Toggled += new global::System.EventHandler (this.OnCbtnDPin10Toggled);
		this.cbtnDPin9.Toggled += new global::System.EventHandler (this.OnCbtnDPin9Toggled);
		this.cbtnDPin8.Toggled += new global::System.EventHandler (this.OnCbtnDPin8Toggled);
		this.cbtnDPin7.Toggled += new global::System.EventHandler (this.OnCbtnDPin7Toggled);
		this.cbtnDPin6.Toggled += new global::System.EventHandler (this.OnCbtnDPin6Toggled);
		this.cbtnDPin5.Toggled += new global::System.EventHandler (this.OnCbtnDPin5Toggled);
		this.cbtnDPin4.Toggled += new global::System.EventHandler (this.OnCbtnDPin4Toggled);
		this.cbtnDPin3.Toggled += new global::System.EventHandler (this.OnCbtnDPin3Toggled);
		this.cbtnDPin2.Toggled += new global::System.EventHandler (this.OnCbtnDPin2Toggled);
		this.cbtnDPin1.Toggled += new global::System.EventHandler (this.OnCbtnDPin1Toggled);
		this.cbtnDPin.Toggled += new global::System.EventHandler (this.OnCbtnDPinToggled);
		this.CBAnalogPin5Mode.Changed += new global::System.EventHandler (this.OnCBAnalogPin5ModeChanged);
		this.CBAnalogPin0Mode.Changed += new global::System.EventHandler (this.OnCombobox19Changed);
		this.HScaleAnalogPinFive.ValueChanged += new global::System.EventHandler (this.OnHScaleAnalogPinFiveValueChanged);
		this.button7.Clicked += new global::System.EventHandler (this.OnButton7Clicked);
		this.button6.Clicked += new global::System.EventHandler (this.OnButton6Clicked);
		this.button5.Clicked += new global::System.EventHandler (this.OnButton5Clicked);
		this.button4.Clicked += new global::System.EventHandler (this.OnButton4Clicked);
		this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
		this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
		this.btnDataRefreshAll.Clicked += new global::System.EventHandler (this.OnBtnDataCollectClicked);
	}
}
