
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vboxMain;
	
	private global::Gtk.Table table1;
	
	private global::Gtk.Button btnCenterPlot;
	
	private global::Gtk.Frame frame1;
	
	private global::Gtk.Alignment GtkAlignment;
	
	private global::Gtk.Table table2;
	
	private global::Gtk.CheckButton checkbuttonMarkerToggle;
	
	private global::Gtk.CheckButton checkbuttonSmoothPlot;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.SpinButton spinbuttonNumberOfSeries;
	
	private global::Gtk.Label GtkLabel4;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Button btnSinglePlot;
	
	private global::Gtk.Button btnTimedPlot;
	
	private global::Gtk.Button btnExit;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vboxMain = new global::Gtk.VBox ();
		this.vboxMain.Name = "vboxMain";
		this.vboxMain.Spacing = 6;
		// Container child vboxMain.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.btnCenterPlot = new global::Gtk.Button ();
		this.btnCenterPlot.CanFocus = true;
		this.btnCenterPlot.Name = "btnCenterPlot";
		this.btnCenterPlot.UseUnderline = true;
		this.btnCenterPlot.Label = global::Mono.Unix.Catalog.GetString ("Best _Fit");
		this.table1.Add (this.btnCenterPlot);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnCenterPlot]));
		w1.LeftAttach = ((uint)(1));
		w1.RightAttach = ((uint)(2));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.table2 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.checkbuttonMarkerToggle = new global::Gtk.CheckButton ();
		this.checkbuttonMarkerToggle.CanFocus = true;
		this.checkbuttonMarkerToggle.Name = "checkbuttonMarkerToggle";
		this.checkbuttonMarkerToggle.Label = global::Mono.Unix.Catalog.GetString ("Show Marker");
		this.checkbuttonMarkerToggle.DrawIndicator = true;
		this.checkbuttonMarkerToggle.UseUnderline = true;
		this.table2.Add (this.checkbuttonMarkerToggle);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2 [this.checkbuttonMarkerToggle]));
		w2.TopAttach = ((uint)(1));
		w2.BottomAttach = ((uint)(2));
		w2.RightAttach = ((uint)(2));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.checkbuttonSmoothPlot = new global::Gtk.CheckButton ();
		this.checkbuttonSmoothPlot.CanFocus = true;
		this.checkbuttonSmoothPlot.Name = "checkbuttonSmoothPlot";
		this.checkbuttonSmoothPlot.Label = global::Mono.Unix.Catalog.GetString ("Smooth Plot");
		this.checkbuttonSmoothPlot.DrawIndicator = true;
		this.checkbuttonSmoothPlot.UseUnderline = true;
		this.table2.Add (this.checkbuttonSmoothPlot);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2 [this.checkbuttonSmoothPlot]));
		w3.RightAttach = ((uint)(2));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.Xalign = 0F;
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Number of Series:");
		this.table2.Add (this.label2);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2 [this.label2]));
		w4.TopAttach = ((uint)(2));
		w4.BottomAttach = ((uint)(3));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.spinbuttonNumberOfSeries = new global::Gtk.SpinButton (1, 32, 1);
		this.spinbuttonNumberOfSeries.CanFocus = true;
		this.spinbuttonNumberOfSeries.Name = "spinbuttonNumberOfSeries";
		this.spinbuttonNumberOfSeries.Adjustment.PageIncrement = 10;
		this.spinbuttonNumberOfSeries.ClimbRate = 1;
		this.spinbuttonNumberOfSeries.Numeric = true;
		this.spinbuttonNumberOfSeries.Value = 1;
		this.table2.Add (this.spinbuttonNumberOfSeries);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2 [this.spinbuttonNumberOfSeries]));
		w5.TopAttach = ((uint)(2));
		w5.BottomAttach = ((uint)(3));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(2));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment.Add (this.table2);
		this.frame1.Add (this.GtkAlignment);
		this.GtkLabel4 = new global::Gtk.Label ();
		this.GtkLabel4.Name = "GtkLabel4";
		this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Options</b>");
		this.GtkLabel4.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel4;
		this.table1.Add (this.frame1);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.frame1]));
		w8.TopAttach = ((uint)(1));
		w8.BottomAttach = ((uint)(2));
		w8.RightAttach = ((uint)(3));
		this.vboxMain.Add (this.table1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.table1]));
		w9.Position = 1;
		// Container child vboxMain.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Homogeneous = true;
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnSinglePlot = new global::Gtk.Button ();
		this.btnSinglePlot.CanFocus = true;
		this.btnSinglePlot.Name = "btnSinglePlot";
		this.btnSinglePlot.UseUnderline = true;
		this.btnSinglePlot.Label = global::Mono.Unix.Catalog.GetString ("Show Single Plot");
		this.hbox1.Add (this.btnSinglePlot);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnSinglePlot]));
		w10.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnTimedPlot = new global::Gtk.Button ();
		this.btnTimedPlot.CanFocus = true;
		this.btnTimedPlot.Name = "btnTimedPlot";
		this.btnTimedPlot.UseUnderline = true;
		this.btnTimedPlot.Label = global::Mono.Unix.Catalog.GetString ("Time Plot");
		this.hbox1.Add (this.btnTimedPlot);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnTimedPlot]));
		w11.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnExit = new global::Gtk.Button ();
		this.btnExit.CanFocus = true;
		this.btnExit.Name = "btnExit";
		this.btnExit.UseUnderline = true;
		this.btnExit.Label = global::Mono.Unix.Catalog.GetString ("Exit");
		this.hbox1.Add (this.btnExit);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnExit]));
		w12.Position = 2;
		this.vboxMain.Add (this.hbox1);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.hbox1]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		this.Add (this.vboxMain);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 742;
		this.DefaultHeight = 675;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.spinbuttonNumberOfSeries.ChangeValue += new global::Gtk.ChangeValueHandler (this.OnSpinbuttonNumberOfSeriesChangeValue);
		this.checkbuttonSmoothPlot.Toggled += new global::System.EventHandler (this.OnCheckbuttonSmoothPlotToggled);
		this.checkbuttonMarkerToggle.Toggled += new global::System.EventHandler (this.OnCheckbuttonMarkerToggleToggled);
		this.btnCenterPlot.Clicked += new global::System.EventHandler (this.OnBtnCenterPlotClicked);
		this.btnTimedPlot.Clicked += new global::System.EventHandler (this.OnBtnTimedPlotClicked);
		this.btnExit.Clicked += new global::System.EventHandler (this.OnBtnExitClicked);
	}
}
